<?php
/**
 *  Created on Feb 18th
 *  File to convert current strings to po file
 *
 *
 */

/**
 * Login
 */

$LANG = array(
'sEntrar' => "Entrar",
'sWelcome' => "Para acceder, introduzca nombre de Empresa, Clave y pulse el boton Aceptar.",
'sIdentEmpresa' => "Identificacion de la empresa",
'sIdentUsuario' => "Identificacion de usuario de la empresa:",
'sWelcome2' => "Para acceder, introduzca nombre de Usuario, Clave y pulse el boton Aceptar",
'sIdIncorrecta' => "Identificacion incorrecta",

'sEmpresa' => "Empresa:",
'sClave' => "Clave:",
'sUsuario' => "Usuario:",

'sIdioma' => "Castellano",
'sSelecIdioma' => "Seleccionar idioma",
'sSelecEmpresa' => "Seleccionar empresa",

/*
 * Formularios
 */
'formNom' => "Nombre",
'formDir' => "Direccion",
'formTel' => "Telefono",
'formPriTel' => "Primer Telefono",
'formSegTel' => "Segundo Telefono",
'formWeb' => "Web",
'formCif' => "Cif",
'formFechHomo' => "Fecha Homologacion",
'formUltRev' => "Ultima Revision",
'formFechDesho' => "Fecha Deshomologacion",
'formAct' => "Activo",
'formCod' => "Codigo",
'formFech' => "Fecha",
'formNumPed' => "Numero Pedido",
'formCom' => "Comentario",
'formAccMej' => "Accion Mejora",
'formProv' => "Proveedor",

/**
 * Errores
 */

'sFalloConexion' => "Error Al conectar a la base de datos",
'sFalloConsulta' => "Error al realizar la busqueda",
'sFalloResultado' => "Error al recuperar los datos",
'sFalloCerrar' => "Error al cerrar la conexion con la base de datos",
'sFalloAuditoria' => "Debe estar realizada la auditoria",
'sErrores' => "Errores",
'sSinAcceso' => "ACCESO PROHIBIDO, NECESARIO LOGEARSE",
'sNoAcceso' => "No tiene permisos para acceder a esta seccion",
'sNoPermisoDoc' => "No tiene permisos para ver el documento",
'sOpcionError' => "Opcion erronea",
'sYaManual' => "Ya existe un Manual",

/**
 * Menu de opciones
 */

'sInicio' => "INICIO",
'sDocumentacion' => "DOCUMENTACION",
'sProveedores' => "PROVEEDORES",
'sMejora' => "ACC. MEJORA",
'sFormacion' => "FORMACION",
'sEquipos' => "EQUIPOS",
'sAuditoria' => "AUDITORIAS",
'sProcesos' => "PROCESOS",
'sIndicadores' => "INDICADORES",
'sEditor' => "EDITOR",
'sAspectos' => "A. AMBIENTALES",
'sLogout' => "CERRAR SESION",

/**
 * Ir al menu de administracion y salir
 */

'sIrAdmin' => "Administracion",
'sSalir' => "Volver",

/**
 * Botones
 */

'sBotonAceptar' => "Aceptar",
'sBotonBusqueda' => "Busqueda",
'sBotonVolver' => "Volver",
'sBotonRevisar' => "Revisar",
'sBotonEditaFicha' => "Editar Ficha",
'sBotonEditar' => "Editar",
'sBotonNuevo' => "Nuevo",
'sBotonMatriz' => "Ver Matriz",
'sBotonDocAx' => "Documentos Anexos",
'sBotonVerFicha' => "Ver Ficha",
'sBotonIndicador' => "Indicadores",
'sBotonFlujog' => "Flujograma",
'sBotonLimpia' => "Limpiar",
'sBotonArea' => "Areas",
'sBotonEqAud' => "Equipo Auditor",
'sBotonPrint' => "Imprimir",
'sBotonVer' => "Ver",
'sBotonNVersion' => "Nueva Version",
'sBotonAprobar' => "Aprobar",
'sBotonTareas' => "Tareas",
'sBotonHist' => "Historico",
'sCambios' => "Guardar Cambios",
'sBotonEnviar' => "Enviar",

/**
 * Menu de administracion
 */

'sAplicacion' => "APLICACION",
'sCalidad' => "CALIDAD",
'sMedio' => "MEDIO AMBIENTE",


'sEstadoAbierto' => "Abierto",

'sHt' => "Hoja Tecnica",
'sPg' => "Procedimiento General",
'sPe' => "Procedimiento Operativo",
'sManual' => "Manual",
'sObjetivos' => "Objetivos",
'sIt' => "Instruccion Tecnica",
'sItm' => "Instruccion Tecnica MedioAmbiente",
'sItma' => "Ficha Requisitos Legales",
'sIAai' => "Analisis Ambiental Inicial",
'sExterno' => "Documentos y formatos",
'sAlta_solicitada' => "Alta solicitada",
'sInscripcion_realizada' => "Inscripcion realizada",
'sYa_inscrito' => "Ya esta inscrito en el curso o ya ha solicitado la inscripcion",
'sBaja_dolicitada' => "Baja solicitada",
'sNo_Inscrito' => "No est inscrito en el curso o ya ha solicitado la baja",
'sIncorrecto' => "La opcion es incorrecta",
'sCurso_no_disponible' => "El curso no esta disponible para inscripciones.",
'sTestSuperado' => "Test superado.",
'sTestNoSuperado' => "Test no superado.",
'sErrorTest' => "ERROR, test no realizado",
'sNecesitaAprobacion' => "El documento debe ser revisado antes de aprobarlo",
'sPolitica' => "Politica Integral",


'sAltav' => "Alta Verificada.",
'sBajav' => "Baja Verificada.",
'sAltay' => "Ya esta verificada su alta",
'sBajay' => "Ya esta verificada su baja",
'sAltan' => "No se ha solicitado ninguna baja",
'sBajan' => "No hay ninguna peticion pedida",


/***********************
 * Titulos de la barra *
 ***********************/

'sTInicio' => 'Inicio',
'sTMensajes' => "Mensajes",
'sContMsj' => "Contenido del Mensaje",
'sTNMensajes' => "Enviar Mensaje Nuevo",
'sTEstMensajes' => "Estadisticas de Mensajes",
'sTBajaMensajes' => "Baja de Mensaje",
'sTVerMensajes' => "Ver Mensaje",
'sTTareas' => "Tareas",
'sTVerTareas' => "Ver Tarea",
'sTBorradores' => "Borradores",
'sTDocumentacion' => "Documentacion",
'sTProveedores' => "Proveedores",
'sTAccionesMejora' => "Acciones de Mejora",
'sTFormacion' => "Formacion",
'sTEquipos' => "Equipos",
'sTAuditorias' => "Auditorias",
'sTProcesos' => "Procesos",
'sTIndicadores' => "Indicadores",
'sTLogout' => "Salir de la Aplicacion",
'sTLogout2' => "Salir de la Aplicacion",
'sTDocVigor' => "Documentacion en Vigor",
'sTDocumentacionHT' => "Documentacion de Hojas Tecnicas",
'sTDocumentacionPG' => "Documentacion de Procedimientos Generales",
'sTDocumentacionPE' => "Documentacion de Procedimientos Operativos",
'sTDocumentacionIT' => "Documentos de Instruccion Tecnica de Calidad",
'sTHIstoricoDoc' => "Histórico de Documentos",
'sTListadoContactos' => "Listado de Contactos",
'sTListadoProv' => "Listado de Proveedores",
'sTListadoProductos' => "Listado de Productos",
'sTListadoIncidencias' => "Listado de Incidencias",
'sTListadoHomologados' => "Listado de Proveedores Homologados",
'sTVerIncidencia' => "Ver Incidencia",
'sTDatosProveedor' => "Ver datos del Proveedor",
'sTDatosProductos' => "Ver datos del Producto",
'sTCriteriosProducto' => 'Ver Criterios del Producto',
'sTAgregaCriterio' => ' Nuevo Criterio',
'sTHistorialProductos' => 'Histco de Productos',
'sTListAccMejora' => 'Listado de Acciones Mejora',
'sTVerSubproceso' => 'Ver Subprocesos',
'sTListIndicadores' => 'Listado de Indicadores',
'sTDocAnexos' => 'Documentos Anexos',
'sTIndicadorProceso' => 'Indicadores de Proceso',
'sTAgregaIndProceso' => ' Indicadores de Proceso',
'sTAgregaDoc' => ' Agregar Documento',
'sTListEquipos' => 'Listado de Equipos',
'sTVerPlanMant' => 'Ver Plan de Mantenimiento',
'sTPlanMant' => 'Plan de Mantenimiento',
'sTRevEquipos' => 'Revision de Equipos',

'sTProgrAnual' => 'Programa Anual',
'sTVerAuditoria' => 'Ver Auditorias',
'sTLEquipoAud' => 'Listado de Equipos Auditores',
'sTAreaAuditoria' => 'Areas de las Auditorias',
'sTAgregaArea' => 'Agregar Area',
'sTPlanAuditoria' => 'Plan de Auditorias',
'sTPlanFormacion' => 'Planes de Formacion',
'sTinscripcion' => 'Inscripcion',
'sTCursos' => 'Cursos',
'sVerCursos' => "Listado de Cursos",
'sTListCursos' => 'Listado de Cursos',
'sListDocente' => 'Listado de Docentes',
'sTListAsistente' => 'Asistentes',
'sTListaAsistCurso' => 'Listado de Asistentes al Curso',
'sTAgregaCurso' => ' Curso de Formacion',

'sTVerHistorico' => 'Inicio-->Mensajes-->Historico',
'sTTareasDoc' => 'Inicio-->Tareas-->Ver Documento',

//Proveedores
'sPListado' => 'Proveedores-->Listado',
'sPNuevo' => 'Proveedores-->Nuevo',
'sPEditar' => 'Proveedores-->Editar',
'sPBaja' => 'Proveedores-->Baja',
'sPProductos' => 'Proveedores-->Productos-->Listado',
'sPProducNuevo' => 'Proveedores-->Productos-->Nuevo',
'sPProducEditar' => 'Proveedores-->Productos-->Editar',
'sPProducCriterios' => 'Proveedores-->Productos-->Criterios',
'sPProductCriteNuevo' => 'Proveedores-->Productos-->Criterios-->Nuevo',
'sPProductCriteRevisar' => 'Proveedores-->Productos-->Criterios-->Revisar',
'sPProductCriteHistorico' => 'Proveedores-->Productos-->Criterios-->Historico',

'sPContactos' => 'Proveedores-->Contactos-->Listado',
'sPContactoNuevo' => 'Proveedores-->Contactos-->Nuevo',
'sPContactoVer' => 'Proveedores-->Contactos-->Ver',
'sPContactoEditar' => 'Proveedores-->Contactos-->Editar',

'sPIncidencias' => 'Proveedores-->Incidencias-->Listado',
'sPIncidenNuevo' => 'Proveedores-->Incidencias-->Nuevo',
'sPIncidenEditar' => 'Proveedores-->Incidencias-->Editar',
'sPIncidenVer' => 'Proveedores-->Incidencias-->Ver',

'sPProducHomologados' => 'Proveedores-->P.Homologados-->Listado',
'sPProducHomoEditar' => 'Proveedores-->P.Homologados-->Editar',
'sPProducHomoVer' => 'Proveedores-->P.Homologados-->Ver',
'sPProducHomoBaja' => 'Proveedores-->P.Homologados-->Baja',


//Equipos
'sEquiListado' => 'Equipos-->Listado',
'sEquiNuevo' => 'Equipos-->Nuevo',
'sEquiVer' => 'Equipos-->Ver',
'sEquiEditar' => 'Equipos-->Editar',
'sEquiPlanMantenimiento' => 'Equipos-->Plan Mantenimiento-->Listado',
'sEquiPlanManPreNuevo' => 'Equipos-->Plan Mantenimiento Preventivo-->Nuevo',
'sEquiPlanManCorrNuevo' => 'Equipos-->Plan Mantenimiento Correctivo-->Nuevo',
'sEquiPlanManVer' => 'Equipos-->Plan Mantenimiento-->Ver',
'sEquiManPreEditar' => 'Equipos-->Mantenimiento Preventivo-->Editar',
'sEquiManCorrEditar' => 'Equipos-->Mantenimiento Correctivo-->Editar',

'sEquiRevisiones' => 'Equipos-->Revisiones',
'sEquiPlanManListado' => 'Equipos-->Plan Mantenimiento-->Listado',

'sEquiCalendario' => 'Equipos-->Calendario',


//Procesos
'sProcNuevo' => 'Procesos-->Nuevo',
'sProcEditar' => 'Procesos-->Editar',
'sProcDetalles' => 'Procesos-->Detalles',
'sProcFicha' => 'Procesos-->Ficha',
'sProcMatriz' => 'Procesos-->Matriz',
'sProcBaja' => 'Procesos-->Baja',
'sProcIndiciadores' => 'Procesos-->Indicadores',
'sProcIndNuevo' => 'Procesos-->Indicadores-->Nuevo',

'sProcDetVer' => 'Procesos-->Detalles-->Ver',
'sProcDetEditar' => 'Procesos-->Detalles-->Editar',
'sProdDetDoc' => 'Procesos-->Detalles-->Documentos Anexos',
'sProdDetDocListado' => 'Procesos-->Detalles-->Documentos Anexos-->Listado',
'sProdDetFlujo' => 'Procesos-->Detalles-->Flujograma',
'sProdDetArea' => 'Procesos-->Detalles-->Area',
'sProdDetRev' => 'Procesos-->Detalles-->Revisar',
'sProdDetAprobar' => 'Procesos-->Detalles-->Aprobar',

'sProdVerFicha' => 'Procesos-->Ver Ficha',
'sProdIndValores' => 'Procesos-->Indicadores-->Valores',
'sProdIndValoresIns' => 'Procesos-->Indicadores-->Insertar Valores',
'sProdIndValIns' => 'Procesos-->Indicadores-->Insertar un Valor',
'sProdIndValEditar' => 'Procesos-->Indicadores-->Editar Valor',
'sProdIndObj' => 'Procesos-->Indicadores-->Objetivos',
'sProdIndObjNuevo' => 'Procesos-->Indicadores-->Objetivos-->Nuevo',
'sProdIndObjEditar' => 'Procesos-->Indicadores-->Objetivos-->Editar',
'sProdIndObjGrafica' => 'Procesos-->Indicadores-->Gráfica',
'sProdIndEliminar' => 'Procesos-->Indicadores-->Eliminar',


//Documentacion
'sTManual' => 'Manuales y Documentacion',
'sTNuevoManual' => 'Documentacion-->Documentacion S.G.-->Manual-->Nuevo Manual',
'sTVerManual' => 'Documentacion-->Documentacion S.G.-->Manual-->Ver Manual',
'sTVerDetallesManual' => 'Documentacion-->Documentacion S.G.-->Ver Detalles Manual',
'sTVerDetallesEditarManual' => 'Documentacion-->Documentacion S.G.-->Editar',
'sTDocVerHistorico' => 'Documentacion-->Ver Historico',
'sTDocVerPermisos' => 'Documentacion-->Ver Permisos',
'sTDocPoliticaNuevo' => 'Documentacion-->Nueva Documentacion de Politica',
'sTDocPoliticaVer' => 'Documentacion-->Ver Documentacion de Politica',
'sTDocPoliticaPermisos' => 'Documentacion-->Permisos de Politica',
'sTDocObjNuevo' => 'Documentacion-->Documentos S.G.-->Nuevo Objetivo',
'sTProgAudit' => 'Documentacion-->Documentos S.G.-->Programacion de Auditorias',
'sTDocProceso' => 'Documentacion-->Documentos S.G.-->Procesos',
'sTDocObjEditar' => 'Documentacion-->Documentos S.G.-->Editar Objetivo',
'sTDocObjSeguimiento' => 'Documentacion-->Documentos S.G.-->Seguimiento Objetivo',
'sTDocSgRevision' => 'Documentacion-->Documentos S.G.-->Revisar',
'sTDocSgAprobar' => 'Documentacion-->Documentos S.G.-->Aprobar',
'sTDocMetas' => 'Documentacion-->Documentos S.G.-->Metas',
'sTDocMetasNueva' => 'Documentacion-->Documentos S.G.-->Nueva Meta',
'sTDocSgNuevaVersion' => 'Documentacion-->Documentos S.G.-->Nueva Version',
'sTDocObjSeguimientoNuevo' => 'Documentacion-->Documentos S.G.-->Nuevo Seguimiento del Objetivo',
'sTDocPgNuevo' => 'Documentacion-->Nuevo Documento P.G.',
'sTDocPgVer' => 'Documentacion-->Ver Documento P.G.',
'sTDocPgListado' => 'Documentacion-->Documentos P.G.-->Listado',
'sTDocRevisar' => 'Documentacion-->Revisar',
'sTDocAprobar' => 'Documentacion-->Aprobar',
'sTDocPgNueVersion' => 'Documentacion-->Nueva Version del Documento',
'sTDocGeneralAsigTarea' => 'Documentacion-->Asignar Tarea',
'sTDocPgPermisos' => 'Documentacion-->Ver Permisos del Documento P.G.',
'sTDocPoListado' => 'Documentacion-->Listado de Procedimientos Operativos',
'sTDocPoNuevo' => 'Documentacion-->Nuevo Documento P.O.',
'sTDocPoDetalles' => 'Documentacion-->Detalles del Documento P.O.',
'sTDocPoPermisos' => 'Documentacion-->Ver Permisos del Documento P.O.',
'sTDocVigorListado' => 'Documentacion-->Listado de Documentacion en Vigor',
'sTDocVigorDetalles' => 'Documentacion-->Detalles del Documento en Vigor',
'sTDocBorradorListado' => 'Documentacion-->Listado de Documentacion de Borradores',
'sTDocBorradorDetalles' => 'Documentacion-->Detalles del Borrador',
'sTDocAAIListado' => 'Documentacion-->Listado de Documentacion de Analisis Ambiental Inicial',
'sTDocAAINuevo' => 'Documentacion-->Nuevo Documento de Analisis Ambiental Inicial',
'sTDocAAIDetalles' => 'Documentacion-->Detalles del Documento de AAI',
'sTDocAAIPermisos' => 'Documentacion-->Permisos del Documento de AAI',
'sTDocPlanambListado' => 'Documentacion-->Listado de Documentacion de Planes de Emergencia Ambiental',
'sTDocPlanemerambNuevo' => 'Documentacion-->Nuevo Documento de Plan de Emergencia Ambiental',
'sTDocPlanemerambVer' => 'Documentacion-->Ver Documento de Plan de Emergencia Ambiental',
'sTDocPlanemerambPermisos' => 'Documentacion-->Permisos del Documento de Plan de Emergencia Ambiental',
'sTDocFRLListado' => 'Documentacion-->Listado de Documentacion de F.R.L.',
'sTDocFrlNuevo' => 'Documentacion-->F.R.L.-->Nuevo',
'sTDocFrlDetalles' => 'Documentacion-->F.R.L.-->Detalles',
'sTDocFrlPermisos' => 'Documentacion-->F.R.L.-->Permisos',
'sTDocLegisList' => 'Documentacion-->Legislación-->Listados',
'sTDocLegNuevo' => 'Documentacion-->Legislacion-->Nuevo',
'sTDocLegEditar' => 'Documentacion-->Legislacion-->Editar',
'sTDocLegCuestNuevo' => 'Documentacion-->Legislacion-->Cuestionario',
'sTDocLegLisVerLey' => 'Documentacion-->Legislacion-->Ver Ley',
'sTDocNormList' => 'Documentacion-->Legislacion-->Normativa',
'sTDocLegisNuevo' => 'Documentacion-->Legislacion-->Normativa-->Nuevo',
'sTDocLegNormVer' => 'Documentacion-->Legislacion-->Detalles Normativa',
'sTDocAsoRegList' => 'Documentacion-->Doc.Asociados-->Registros',
'sTDocLegRegList' => 'Documentacion-->Doc.Asociados-->Registros-->Listados',
'sTDocAsoFormList' => 'Documentacion-->Doc.Asociados-->Documentos y Formatos',
'sTDocAsoFormNuevo' => 'Documentacion-->Doc.Asociados-->Nuevo Formato',
'sTDocAsoFormDetalles' => 'Documentacion-->Doc.Asociados-->Detalles',
'sTDocAsoFormPermisos' => 'Documentacion-->Doc.Asociados-->Permisos',

//Acc Mejora
'sTMejoraListado' => 'Listado de Acciones de Mejora',
'sTMejoraNuevo' => 'Accion Mejora-->Nueva',
'sTMejoraEditar' => 'Accion Mejora-->Editar',
'sTMejoraSelecUsuario' => 'Accion Mejora-->Seleccionar Usuario',
//Formacion
'sTFormFichListado' => 'Formacion-->Recursos-->Listado de Fichas Personales',
'sTFormFichaNuevo' => 'Formacion-->Recursos-->Nueva Ficha Personal',
'sTFormFichaEditar' => 'Formacion-->Recursos-->Editar Ficha Personal',
'sTFormFichaDatosPer' => 'Formacion-->Recursos-->Ficha Personal-->Datos Personales',
'sTFormFichaInc' => 'Formacion-->Recursos-->Ficha Personal-->Incorporaci�n',
'sTFormFichaFor' => 'Formacion-->Recursos-->Ficha Personal-->Formacion',
'sTFormFichaPreForm' => 'Formacion-->Recursos-->Ficha Personal-->Pre-formacion',
'sTFormFichaIdiomas' => 'Formacion-->Recursos-->Ficha Personal-->Idiomas',
'sTFormFichaCursos' => 'Formacion-->Recursos-->Ficha Personal-->Cursos',
'sTFormFichaFormacionTec' => 'Formacion-->Recursos-->Ficha Personal-->Formacion Tecnica',
'sTFormFichaExp' => 'Formacion-->Recursos-->Ficha Personal-->Experiencia Laboral',
'sTFormFichaCambPerfil' => 'Formacion-->Recursos-->Ficha Personal-->Cambio de Perfil',
'sTFormFichaCambDept' => 'Formacion-->Recursos-->Ficha Personal-->Cambios de Departamento',
'sTFormReqpuestoListado' => 'Formacion-->Recursos-->Listado de Requirimientos del Puesto',
'sTFormReqPuestoNuevo' => 'Formacion-->Recursos-->Nuevo Requerimiento para el Puesto',
'sTFormCursosListado' => 'Formación-->Listado de Cursos',
'sTFormCursosNuevo' => 'Formación-->Cursos-->Nuevo',
'sTFormCursosEditar' => 'Formación-->Cursos-->Editar',
'sTFormInscripcionListado' => 'Formación-->Listado de Inscripciones',
'sTFormInscAsistentes' => 'Formación-->Inscripciones-->Asistentes',
'sTFormInscDetalles' => 'Formación-->Inscripciones-->Detalles',
'sTFormInscAlta' => 'Formación-->Inscripciones-->Alta',
'sTFormPlanesListado' => 'Formacion-->Listado de Planes de Formacion',
'sTFormPlanesNuevo' => 'Formacion-->Nuevo Plan de Formacion',
'sTFormPlanesEditar' => 'Formacion-->Editar Plan de Formacion',
'sTFormPlanesCursosPlan' => 'Formacion-->Planes Formacion-->Cursos Plan',
'sTFormPlanesCursosPlanNuevo' => 'Formacion-->Planes Formacion-->Cursos Plan-->Nuevo',
'sTFormPlanesCursosPlanNuevoAgregar' => 'Formacion-->Planes Formacion-->Cursos Plan-->Agregar',
'sTFormPlanesCursosPlanNuevoMsj' => 'Formacion-->Planes Formacion-->Cursos Plan-->Nuevo Mensaje',
'sTFormPlanesCursosPlanEditar' => 'Formacion-->Planes Formacion-->Cursos Plan-->Editar',
'sTFormPlanesCursosPlanDetalles' => 'Formacion-->Planes Formacion-->Cursos Plan-->Detalles',
'sTFormPlanesCursosPlanAsist' => 'Formacion-->Planes Formacion-->Cursos Plan-->Asistentes',
'sTFormPlanesCursosPlanAsistAlumNuevo' => 'Formacion-->Planes Formacion-->Cursos Plan-->Alumno Nuevo',
'sTFormPlanesCursosPlanProfesores' => 'Formacion-->Planes Formacion-->Cursos Plan-->Profesores',
'sTFormPlanesCursosPlanProfeNuevo' => 'Formacion-->Planes Formacion-->Cursos Plan-->Nuevo Profesor',
'sTFormPlanesCursosPlanProfeEditar' => 'Formacion-->Planes Formacion-->Cursos Plan-->Editar Profesor',
'sTFormPlanesCursosPlanSubir' => 'Formacion-->Planes Formacion-->Cursos Plan-->Subir Hoja de Firmas',

//indicadores
'sTIndListado' => 'Indicadores-->Listado de Indicadores',
'sTIndNuevo' => 'Indicadores-->Nuevo Indicador',
'sTIndMatriz' => 'Indicadores-->Matriz',
'sTIndGrafica' => 'Indicadores-->Grafica',
'sTIndGraficaVer' => 'Indicadores-->Ver Grafica',
'sTIndEditar' => 'Indicadores-->Editar',
'sTIndValores' => 'Indicadores-->Valores',
'sTIndInsValores' => 'Indicadores-->Insertar Valores',
'sTIndInsUnValor' => 'Indicadores-->Insertar Un Valor',
'sTIndEditarValor' => 'Indicadores-->Editar Valores',
'sTIndObjNuevo' => 'Indicadores-->Objetivos-->Nuevo Objetivo',
'sTIndObjEditar' => 'Indicadores-->Objetivos-->Editar Objetivo',
'sTIndObjMetas' => 'Indicadores-->Objetivos-->Metas',
'sTIndObjRevisar' => 'Indicadores-->Objetivos-->Revisar',
'sTIndObjAprobar' => 'Indicadores-->Objetivos-->Aprobar',
'sTIndObjListado' => 'Indicadores-->Listado de Objetivos',

//Aambientales
'sTAambRevListado' => 'A.Ambientales-->Listado de Aspectos Ambientales',
'sTAambNuevo' => 'A.Ambientales-->Nuevo Aspecto Ambiental',
'sTAambEditar' => 'A.Ambientales-->Editar Apsecto Ambiental',
'sTAambRevemerListado' => 'A.Ambientales-->Listado de Aspectos Ambientales de Emergencia',
'sTAambEmerNuevo' => 'A.Ambientales-->A.Amb.Emergencia-->Nuevo',
'sTAambEmerEditar' => 'A.Ambientales-->A.Amb.Emergencia-->Editar',
'sTAmbMatrizVer' => 'A.Ambientales-->Matriz',

//administracion
'sTAdmin' => 'Administracion',
'sTAdminUsuarioListado' => 'Administracion-->Aplicacion-->Listado de Usuarios',
'sTAdminUsuarioNuevo' => 'Administracion-->Aplicacion-->Usuario Nuevo',
'sTAdminUsuarioFicha' => 'Administracion-->Aplicacion-->Usuarios-->Seleccionar Ficha',
'sTAdminUsuarioReq' => 'Administracion-->Aplicacion-->Usuarios-->Seleccionar Requisito',
'sTAdminUsuarioEditar' => 'Administracion-->Aplicacion-->Usuarios-->Editar Usuario',
'sTAdminUsuarioPass' => 'Administracion-->Aplicacion-->Usuarios-->Cambiar Password',

'sTAdminPerfListado' => 'Administracion-->Aplicacion-->Listado de Perfiles',
'sTAdminPerfNuevo' => 'Administracion-->Aplicacion-->Perfiles-->Nuevo Perfil',
'sTAdminPerfEditar' => 'Administracion-->Aplicacion-->Perfiles-->Editar Perfil',
'sTAdminPerfCopiar' => 'Administracion-->Aplicacion-->Perfiles-->Copiar Perfil',

'sTAdminMsjList' => 'Administracion-->Aplicacion-->Listado de Mensajes',
'sTAdminMsjNuevo' => 'Administracion-->Aplicacion-->Nuevo Mensaje',

'sTAdminTareasList' => 'Administracion-->Aplicacion-->Listado de Tareas',

'sTAdminMenusList' => 'Administracion-->Aplicacion-->Listado de Menus',
'sTAdminMenuEstruc' => 'Administracion-->Aplicacion-->Menus-->Estructura',
'sTAdminMenuNuevo' => 'Administracion-->Aplicacion-->Menus-->Nuevo',
'sTAmindMenuBotones' => 'Administracion-->Aplicacion-->Menus-->Botones',
'sTAdminMenuBotonesNuevo' => 'Administracion-->Aplicacion-->Menus-->Botones-->Nuevo',
'sTAdminMenuBotonesEditar' => 'Administracion-->Aplicacion-->Menus-->Botones-->Editar',
'sTAdminMenuBotonesIdioma' => 'Administracion-->Aplicacion-->Menus-->Botones-->Idiomas',
'sTAdminMenuBotonesIdiomaEditar' => 'Administracion-->Aplicacion-->Menus-->Botones-->Editar Idioma',
'sTAdminMenuIdioma' => 'Administracion-->Aplicacion-->Menus-->Idiomas',
'sTAdminMenuIdiomaEditar' => 'Administracion-->Aplicacion-->Menus-->Editar Idioma',
'sTAdminMenuEditar' => 'Administracion-->Aplicacion-->Menus-->Editar',

'sTAdminIdiomaList' => 'Administracion-->Aplicacion-->Listado de Idiomas',
'sTAdminIdiomaNuevo' => 'Administracion-->Aplicacion-->Idioma Nuevo',

'sTAdminDocSGList' => 'Administracion-->Documentos-->Listado de Documentos S.G.',

'sTAdminRegistrosList' => 'Administracion-->Documentos-->Listado de Registros',

'sTAdminNormativaList' => 'Administracion-->Documentos-->Listado de tipos de documentos y formatos',

'sTAdminTipomejoraList' => 'Administracion-->Listado de Tipos de Acci�n de Mejora',
'sTAdminTipomejoraNuevo' => 'Administracion-->Tipos de Acc.Mejora-->Nueva',
'sTAdminTipomejoraEditar' => 'Administracion-->Tipos de Acc.Mejora-->Editar',

'sTAdminTipoareasList' => 'Administracion-->Listado de Tipos de Area',
'sTAdminTipoareasNuevo' => 'Administracion-->Tipos de Areas-->Nuevo',
'sTAdminTipoareasEditar' => 'Administracion-->Tipos de Areas-->Editar',

'sTAdminTiposambList' => 'Administracion-->Listado de Tipos Ambientales de la Aplicacion',
'sTAdminTiposambNuevo' => 'Administracion-->Tipos Ambientales de la Aplicacion-->Nuevo',
'sTAdminTiposambEditar' => 'Administracion-->Tipos Ambientales de la Aplicacion-->Editar',

'sTAdminLegList' => 'Administracion-->Legislacion Aplicable',
'sTAdminLegListPreg' => 'Administracion-->Legislacion Aplicable-->Preguntas',
'sTAdminLegListPregNueva' => 'Administracion-->Legislacion Aplicable-->Preguntas-->Nueva',
'sTAdminLegListPregBaja' => 'Administracion-->Legislacion Aplicable-->Preguntas-->Baja',

'sTAdminTiposimpList' => 'Administracion-->Listado de Tipos de Impactos Ambientales',
'sTAdminTiposimpNuevo' => 'Administracion-->Tipos de Impactos Ambientales-->Nuevo',
'sTAdminTiposimpEditar' => 'Administracion-->Tipos de Impactos Ambientales-->Editar',

'sTAdminFormCurList' => 'Administracion-->Formacion-->Listado de Tipos de Cursos',
'sTAdminFormCurNuevo' => 'Administracion->Formacion-->Tipos de Cursos-->Nuevo',
'sTAdminFormCurEditar' => 'Administracion-->Formacion-->Tipos de Cursos-->Editar',

'sTAdminTipoDocList' => 'Administracion-->Listado de Tipos de Documentos',
'sTAdminTipoDocNuevo' => 'Administracion-->Tipos de Documentos-->Nuevo',
'sTAdminTipoDocEditar' => 'Administracion-->Tipos de Doumentos-->Editar',
'sTAdminTipoDocPermisos' => 'Administracion-->Tipos de Documentos-->Permisos',

'sTAdminAspecMagList' => 'Administracion-->Aspectos Ambientales-->Cantidad-->Listado',
'sTAdminAspecMagNuevo' => 'Administracion-->Aspectos Ambientales-->Cantidad-->Nueva',
'sTAdminAspecMagEditar' => 'Administracion-->Aspectos Ambientales-->Cantidad-->Editar',

'sTAdminAspecGravList' => 'Administracion-->Aspectos Ambientales-->Severidad-->Listado',
'sTAdminAspecGravNuevo' => 'Administracion-->Aspectos Ambientales-->Severidad-->Nueva',
'sTAdminAspecGravEditar' => 'Administracion-->Aspectos Ambientales-->Severidad-->Editar',

'sTAdminAspecFreList' => 'Administracion-->Aspectos Ambientales-->Frec./Probabilidad-->Listado',
'sTAdminAspecFreNuevo' => 'Administracion-->Aspectos Ambientales-->Frec./Probabilidad-->Nuevo',
'sTAdminAspecFreEditar' => 'Administracion-->Aspectos Ambientales-->Frec./Probabilidad-->Editar',

'sTAdminAspecFormList' => 'Administracion-->Aspectos Ambientales-->Formulas',
'sTAdminAspecFormEditar' => 'Administracion-->Aspectos Ambientals-->Formulas-->Editar',

'sTAdminAspecProbList' => 'Administracion-->Aspectos Ambientales-->Listado de Tipos de Probabilidad',
'sTAdminAspecProbNuevo' => 'Administracion-->Aspectos Ambientales-->Probabilidad-->Nuevo',
'sTAdminAspecProbEditar' => 'Administracion-->Aspectos Ambientales-->Probabilidad-->Editar',

'sTAdminAspecSeverList' => 'Administracion-->Aspectos Ambientales-->Sever./Emergencia-->Listado',
'sTAdminAspecServNuevo' => 'Administracion-->Aspectos Ambientales-->Sever./Emergencia-->Nueva',
'sTAdminAspecServEditar' => 'Administracion-->Aspectos Ambientales-->Sever./Emergencia-->Editar',

'sTAdminAyudaList' => 'Administracion-->Listado de los registros de Ayuda',
'sTAdminAyudaNuevo' => 'Administracion-->Ayuda-->Nueva',
'sTAdminAyudaEditar' => 'Administracion-->Ayuda-->Editar',

'sTAdminMod' => 'Administracion-->Permisos de los modulos',

'sTAudiListado' => 'Auditorias-->Programa Anual-->Listado',
'sTAudiNuevo' => 'Auditorias-->Programa Anual-->Nuevo',
'sTAudiEditar' => 'Auditorias-->Programa Anual-->Editar',
'sTAudiVigente' => 'Auditorias-->Programa Anual-->Hacer Vigente',
'sTAudiCopiar' => 'Auditorias-->Programa Anual-->Copiar',
'sTAudiVer' => 'Auditorias-->Programa Anual-->Listado de Auditorias',
'sTAudiAudiEditar' => 'Auditorias-->Programa Anual-->Auditorias-->Editar',
'sTAudiAudiDetalles' => 'Auditorias-->Programa Anual-->Auditorias-->Detalles',
'sTAudiAudiPlan' => 'Auditorias-->Programa Anual-->Auditorias-->Plan de Auditoria',
'sTAudiAudiEquipoAudi' => 'Auditorias-->Programa Anual-->Auditorias-->Equipo de Auditores',
'sTAudiAudiAdjunto' => 'Auditorias-->Programa Anual-->Auditorias-->Equipo de Auditores-->Subir Fichero',
'sTAudiAudiVerAdjunto' => 'Auditorias-->Programa Anual-->Auditorias-->Equipo de Auditores-->Ver Fichero',
'sTAudiAudiHorario' => 'Auditorias-->Programa Anual-->Auditorias-->Horarios',
'sTAudiAudiHorarioNuevo' => 'Auditorias-->Programa Anual-->Auditorias-->Horarios-->Nuevo',
'sTAudiAudiHorarioEditar' => 'Auditorias-->Programa Anual-->Auditorias-->Horarios-->Editar',
'sTAudiAudiInforme' => 'Auditorias-->Programa Anual-->Auditorias-->Informe',
'sTAudiAudiRevision' => 'Auditorias-->Programa Anual-->Auditorias-->Revision',
'sTAudiVigor' => 'Auditorias-->Programa en Vigor-->Listado',
'sTAudiVigorNuevo' => 'Auditorias-->Programa en Vigor-->Nuevo',
'sTAudiVigorEditar' => 'Auditorias-->Programa en Vigor-->Editar',
'sTAudiVigorDetalles' => 'Auditorias-->Programa en Vigor-->Detalles',

'sTListRegistro' => 'Listado de Registros',
'sTDocExterna' => 'Documentacion Externa',
'sTFichaPersonal' => 'Ficha del Personal',
'sTRequisito' => 'Requisitos del Puesto',
'sTCalendarioA' => 'Calendario Anual',
'sTNuevoDoc' => 'Nuevo Documento',
//'Nuevo Documento',
// 'Nuevo Documento',
'sTNuevaVersionDoc' => 'Nueva Version del Documento',
//'Nueva Version del Documento',
//'Nueva Version del Documento',
'sTEditarDoc' => 'Editar Documento',
//'Editar Documento',
// 'Editar Documento',
'sTAprobarDoc' => 'Aprobar el Documento',
'sTRevisarDoc' => 'Revisar el Documento',
'sTAsignaTarea' => 'Asignar Tarea',
'sTAgregaProv' => 'Nuevo Proveedor',
'sTAgregaInc' => 'Nueva Incidencia',
//' Incidencia',
'TAgregaContacto' => 'Nuevo Contacto',
//    ' Contacto',
'sTAgregaProd' => 'Nuevo Producto',
//' Producto',
'sTEditProv' => 'Editar Informacion del Proveedor',
'sTEditInc' => 'Editar Incidencia',
//'Editar Incidencia',
'sTEditContacto' => 'Editar Contacto',
//'Editar Contacto',
'sTVerInfoProd' => "Ver Informacion del Producto",
'sTEditProdInfo' => 'Editar Informacion del Producto',
//'Editar Informacion del Producto',
'sTVerInfoProv' => 'Ver Informacion del Proveedor',
'sTVerInfoContacto' => 'Ver Informacion de los Contactos',
//                    'Ver Datos del Producto',
'sTRevProducto' => 'Revision del Producto',


'sTDarAlta' => 'Dar de Alta',
'sTDarBaja' => 'Dar de Baja',
//     'Revision del Producto',
'sTListaAccMej' => 'Nuevo Listado de Acciones de Mejora',
'sTEditAccMej' => 'Editar Acciones de Mejora',
'sAccVerificada' => "Accion Verificada",
'sAccYaCerrada' => "La accion ya está cerrada",
'sAccCerrada' => "Accion Cerrada",
'sTNuevoProceso' => 'Nuevo Proceso',
'sTNuevoIndicador' => 'Nuevo Indicador',
'sTEditaProceso' => 'Editar Proceso',
'sTEditaIndicador' => 'Editar Indicador',
'sTVerFichaProceso' => 'Ver Fichas del Proceso',
'sTCatalgProceso' => 'Catalogo de Procesos',
'sTArbolProceso' => 'Arbol de Procesos',
'sTEditaContenido' => 'Editar Contenido',
'sTDarAltaDoc' => 'Dar de Alta el Documento',
'sTDarBajaDoc' => 'Dar de Baja el Documento',
'sTDarAltaIndProc' => 'Añadir Indicador de Proceso',
'sTDarBajaIndProc' => 'Dar de Baja el Indicador de Proceso',
'sTVerFichaProc' => 'Ver Ficha de Proceso',
'sTVerMatrizProc' => 'Ver Matriz de Procesos',
'sTVerFlujog' => 'Ver Flujograma',
'sTNuevoEquipo' => 'Nuevo Equipo',
'sTEditDatosEq' => 'Editar Datos del Equipo',
'sTMantPrev' => ' Mantenimiento Preventivo',
'sTMantCorr' => ' Mantenimiento Correctivo',
'sTEditMantCorr' => 'Agregar Nuevo Plan de Mantenimiento Correctivo',
'sTEditMantPrev' => 'Agregar Nuevo Plan de Mantenimiento Preventivo',
'sTVerDatosEquipo' => 'Ver Datos del Equipo',
'sTBajaEquipo' => 'Dar de Baja Un Equipo',
'sTDetallesMant' => 'Detalles del Plan de  Mantenimiento',
'sTNuevoProg' => 'Nuevo Programa de Auditoria',
'sTEditProg' => 'Editar Programa de Auditoria',
'sTNuevaAudit' => 'Nueva Auditoria',
'sTNuevoAuditor' => 'Nuevo Auditor',
'sTEditAudit' => 'Editar Auditoria',
'sTEditPlanAudit' => 'Nuevo Plan de Auditoria',
'sTEditInformeA' => 'Informe de Auditoria',
'sTDarBajaPrg' => 'Dar de baja un Programa',
'sTDarBajaAud' => 'Dar de Baja una Auditoria',
'sTHacerVigente' => 'Hacer Vigente un Programa de Auditoria',
'sTAltaArea' => 'Dar de Alta un Area',
'sTBajaArea' => 'Dar de Baja un Area',
'sTDetallesAudit' => 'Detalles de la Auditoria',
'sTPrintInforme' => 'Imprimir Informe',
'sTMejora' => 'Mejora',
'sTIndicador' => 'Indicadores',
'sTAuditoria' => 'Auditorias',
'sTAspectosA' => 'Aspectos Ambientales',
'sTBorrador' => 'Borradores',
'sTDocHT' => 'Documentacion de Hojas Técnicas',
'sTDocPG' => 'Documentos de Procedimiento General',
'sTDocIT' => 'Documentacion de Instruccion Tecnica.',
'sTDocPolitica' => 'Documentacion de Politica',
'sTDocObjetivos' => 'Documentacion-->Documentos S.G.-->Objetivos',
'sTNuevoMsg' => 'Nuevo Mensaje',
'sTHistorial' => 'Histórico',
'sTLegislacion' => 'Legislacion',
'sTPlanesForm' => 'Planes de Formacion',
'sTInscripcion' => 'Inscripcion',
'sTCursosForm' => 'Cursos de Formacion',
'sTListDocente' => 'Listado de Docentes',
'sTAsistente' => 'Asistentes',
'sTListAssistente' => 'Listado de Asistentes al Curso',
'TNuevaLeg' => 'Nueva Legislacion',
'sTEditLeg' => 'Editar Legislacion',
'sTVerLeg' => 'Ver Legislacion',
'sTVerCuestionario' => 'Ver Cuestionario',
'sTFormularios' => 'Formularios',
'sTHistPreg' => 'Histórico de Preguntas',
'sTAdminDocs' => 'Administracion de Documentos',
'sTAdminUsuario' => 'Administracion de Usuarios',
'sTAdminPerfiles' => 'Administracion de Perfiles',
'sTAdminMsg' => 'Administracion de Mensajes',
'sTAdminTareas' => 'Administracion de Tareas',
'sTAdminAreas' => 'Administracion de Areas',
'sTAdminClientes' => 'Administracion de Clientes',
'sTAdminAccMej' => 'Administracion de Acciones Mejora',
'sTAdminCrit' => 'Administracion de Criterios',
'sTHistMsg' => 'Historico de Mensajes',
'sTAdminReg' => 'Administracion de Registros',
'sTAdminNorm' => 'Administracion de Normativas',
'sTNuevoCrit' => 'Nuevo Criterio',
'sTNuevoUsuario' => 'Nuevo Usuario',
'sTNuevoCliente' => 'Nuevo Cliente',
'sTNuevoPerfil' => 'Nuevo Perfil',
'sTNuevoArea' => 'Nueva Area',
'sTNuevaMejora' => 'Nueva Accion de Mejora',
'sTNuevoCurso' => 'Nuevo Curso',
'sTEditCriterio' => 'Editar Criterio',
'sTEditMsg' => 'Editar Mensaje',
'sTEditArea' => 'Editar Area',
'sTEditUsuario' => 'Editar Usuario',
'sTEditPerfil' => 'Editar Perfil',
'sTEditCliente' => 'Editar Cliente',
'sTClaveUsuario' => 'Cambiar Clave de Usuario',
'sTPermisos' => 'Permisos',
'sTNuevoPlanForm' => 'Nuevo Plan de Formacion',
'sTNuevoDocente' => 'Nuevo Docente',
'sTNuevoAlumno' => 'Nuevo Alumno',
'sTMandarMsg' => 'Nuevo Mensaje a los Usuarios',
'sTEditDocente' => 'Editar Informacion del Docente',
'sTEditPlanCurso' => 'Editar Plan del Curso',
'sNuevoPlanCurso' => 'Nuevo Plan del Curso',
'sTEditPlan' => 'Editar Plan de Formacion',
'sTEditInfoCurso' => 'Editar Informacion Sobre el Curso',
'sTEditDetallesPlan' => ' Editar los Detalles de la Planificacion del Curso',
'sTDetallesCurso' => 'Detalles del Curso',
'sTDetallesDoc' => 'Informacion sobre el Documento',
'sTDocInfo' => 'Informacion sobre el Documento',
'sTVerMensaje' => 'Ver Mensaje',
'sTVerTarea' => 'Inicio-->Ver Tarea',
'sTConfirmaAlta' => 'Confirmar Alta',
'sTConfirmaBaja' => 'Confirmar Baja',
'sTAltaCurso' => 'Alta del Curso',
'sTBajaCruso' => 'Baja del Curso',
'sTHistMsgUsuario' => 'Histórico de Mensajes del Usuario',
'sTDarBajaPerfiles' => 'Dar de Baja Perfiles',
'sTDarbajaUsuario' => 'Dar de Baja Usuarios',
'sTDarBajaTareas' => 'Dar de Baja Tareas',
'sTDarBajaDocs' => 'Dar de Baja Documentos',
'sTDarAltaDocs' => 'Dar de Alta Documentos',
'sTEditorDocs' => 'Editor de Documentos',
'sTCalentario' => 'Calendario',
'sTFormulario' => 'Formulario',
'sTEliminar' => 'Eliminar',
'sTAceptar' => 'Aceptar',
'sTAceptarDocs' => 'Aceptar Documentos',
'sTAceptarPerfil' => 'Aceptar el Perfil',
'sTVerDoc' => 'Ver Documento',
'sTSeleccUsuario' => 'Seleccionar Usuario',
'sTFila' => 'Fila',
'sTopCorrecta' => 'Operacion Correcta',
'sTPoliticaC' => "Politica de Calidad",
'sTPoliticaI' => "Politica Integral",
'sTPoliticaA' => "Politica Ambiental",
'sAdminTAreas' => "Administrar Tipos de Area",
'sAdminTAmb' => "Administrar Ambitos de Aplicacion",
'sTAdminPolC' => "Politica de Calidad",
'sTAdminPolM' => "Politica Medioambiental",
'sTNuevoCal' => "Añadir Documento de Politica de Calidad",
'sTNuevoAmb' => "Nuevo Documento de Politica MedioAmbiental",
'sTAdminLey' => "Administracion de la Legislacion Aplicable",
'sTNuevoMsj' => "Nuevo Mensaje",
'sTNuevoFichaP' => "Nueva Ficha de Personal",
'sTEditFichaP' => "Editar Ficha de Personal",
'sTEditDatosP' => "Editar Datos Personales",
'sTExterno' => "Documentos y formatos",
'sTEditDForm' => "Editar Datos de Formacion",
'sTEditPreForm' => "Editar Datos de Pre-formacion",
'sTEditIdioma' => "Editar Conocimiento de Idiomas",
'sTEditCurso' => "Editar Cursos Realizados",
'sTAddCurso' => "Añadir Curso",
'sTVerFTec' => "Formacion Técnica",
'sTVerEL' => "Experiencia Laboral",
'sTCambiosP' => "Editar Cambios de Perfil",
'sTVerP' => "Cambios de Perfil",
'sTCambiosDpt' => "Cambios de Departamento",
'sTExpL' => "Experiencia Laboral",
'sTFormTec' => "Formacion Tecnica",
'sTNuevoFT' => "Añadir Formacion Tecnica",
'sTEditFT' => "Editar Formacion Tecnica",
'sTNuevoELab' => "Añadir Experiencia Laboral",
'sEditELab' => "Editar Experiencia Laboral",
'sEditCambioP' => "Editar Cambio de Perfil",
'sEditCambioDpt' => "Editar Cambio de Departamento",
'sEditNuevoCDpt' => "Nuevo Cambio de Departamento",
'sTVerFormReq' => "Formacion",
'sTNuevoFormReq' => "Añadir Formacion",
'sTNuevoFTReq' => "Añadir Formacion Tecnica",
'sTEditFTReq' => "Editar Requisitos del Puesto",
'sTEditCompReq' => "Editar Competencias del Puesto",
'sTNuevaCompReq' => "Añadir Nuevas Competencias del Puesto",
'sTEditFormReq' => "Editar Formacion",
'sTVerCompReq' => "Competencias del Puesto",
'sTNuevoPromReq' => "Añadir Requisitos del Puesto de Promocion",
'sEditReqPuesto' => "Editar Requisitos del Puesto",
'sTEditarReqProm' => "Editar Requisitos del Puesto de Promocion",
'sTNuevoMP' => "Nuevo Plan de Mantenimiento Preventivo",
'sTNuevoMC' => "Nuevo Plan de Mantenimiento Correctivo",
'sTEditMP' => "Nuevo Plan de Mantenimiento Preventivo",
'sTEditMC' => "Nuevo Plan de Mantenimiento Correctivo",
'sTDetallesProc' => "Detalles del Proceso",
'sTNuevoInd' => "Nuevo Indicador de Proceso",
'sTVerValoresInd' => "Ver Valores del Indicador",
'sTNuevoValorInd' => "Nuevo Valor del Indicador",
'sTListObj' => "Listado de Objetivos",
'sTVerObjetivos' => "Objetivos",
'sTAddIndProc' => "Agregar Indicadores de Proceso",
'sTVerMatrizInd' => "Ver Matriz de Indicadores",
'sTEditObjetivo' => "Editar Objetivo",
'sTNuevoObjInd' => "Nuevo Objetivo",
'sTMatrizAmb' => "Matriz de Aspectos Ambientales",
'sTAspAmb' => "Revision de Aspectos Ambientales",
'sTNuevoAspAmb' => "Nuevo Aspecto Ambiental",
'sTEditAspAmb' => "Editar Aspecto Ambiental",
'sTPermisosDoc' => "Permisos de Documentos",
'sTCopiarPerfil' => "Copiar Perfil",
'sCreadoPerfil' => "Perfil Creado",
'sNoCreadoPerfil' => "No se pueden crear mas perfiles",
'sTAdmNormativa' => "Administracion de Normativas",
'sTNuevaNorm' => "Nueva Normativa",
'sTEditNorm' => "Editar Normativa",
'sTSubirFichero' => "Subir Fichero",
'sTHistPAmb' => "Historico de Politica Ambiental",
'sTHistPCal' => "Historico de Politica de Calidad",
'sTAdministracionAp' => "Administracion de la Aplicacion",
'sTAdministracionC' => "Administracion del Modulo de Calidad",
'sTAdministracionAm' => "Administracion del Modulo de Medio Ambiente",
'sTExito' => "Operacion Realizada con Exito",
'sTFichasMA' => "Fichas de Requisitos Legales",
/*************
 * Listados  *
 *************/

'sNoFila' => "Ninguna fila encontrada",
'sElemPag' => "Numero de Elementos por Pagina",
'sAltaBaja' => "Alta/Baja",
'sAlta' => "Alta",
'sBaja' => "Baja",
'sTodos' => "Todos",
'sAnterior' => "Anterior",
'sAltFechOrd' => "flecha de ordenacion ascendente",

/******************
 * Mantenimientos *
 ******************/
'sMantProx' => "Proximo Mantenimiento Preventivo Previsto: &nbsp,&nbsp,&nbsp,&nbsp,",


/************
 * Graficas *
 ************/
'sGrafID' => "Grafica del indicador",
'sOfProc' => "del proceso",
'sGrafYear' => "Grafica de los 12 ultimos meses",
'sGrafYearAc' => "Grafica del a�o actual",
'sGrafHist' => "Grafica del historico",
'sNoPuedeGraf' => "El indicador no posee valores para poder hacer la grafica",


/**********************
 * Tablas de mensajes *
 **********************/

'sTablaMensajes' => "Mensajes",
'sMensajesID' => 'mensajes.id',
'sMensajesDest' => 'mensajes.destinatario',
'sElemxPag' => "Numero Elementos por Pagina",
'sEstadoMejora' => "Estado",
'sMejoraTodos' => "Todos",
'sMejoraCerrada' => "Cerrada",
'sMejoraAbierta' => "Abierta",
'sMejoraAnterior' => "Anterior",
'sIzquierda' => "<<",
'sDerecha' => ">>",
'sFilaActual' => "Actualizada fila",


/****************
 * Proveedores  *
 ****************/

'sProvNombre' => "Nombre:",
'sProvDireccion' => "Direccion:",
'sProvTelefono' => "Telefono:",
'sProvWeb' => "Web:",
'sProvCif' => "CIF:",
'sProvFechaHomol' => "Fecha de Homologacion:",
'sProvUltimaRevHom' => "Ultima fecha de revision homologacion:",
'sProvDeshomol' => "Fecha Deshomologacion:",
'sProvError' => "Error",


/***************
 * Incidencias *
 ***************/

'sIncFecha' => "Fecha:",
'sIncPedido' => "Numero Pedido:",
'sIncComentario' => "Comentario:",
'sIncError' => "Error",


/***************
 * Contactos   *
 ***************/

'sCtcNombre' => "Nombre:",
'sCtcTlf1' => "Primer Telefono:",
'sCtcTlf2' => "Segundo Telefono:",
'sCtcFax' => "Fax:",
'sCtcMovil' => "Movil:",
'sCtcError' => "Error",

/**************
 * Productos  *
 **************/

'sProdDesc' => "Descripcion del Producto:",
'sProdValorH' => "Valor Homologacion:",
'sProdProv' => "Proveedor:",
'sProdActivo' => "Activo:",
'sProdError' => "Error",
'sProdRevisado' => "Revisado Correctamente",

/**************
 * Criterios  *
 **************/

'sCritQuitar' => "Criterio Quitado",
'sCritPoner' => "Criterio Añadido",
'sCritNombre' => "Nombre",
'sCritValoracion' => "Valoracion",
'sCritPuntuacion' => "Puntuacion Total:",
'sCritNoHomol' => "Proveedor no homologado:",
'sCritHomol' => "Proveedor homologado:",


/**************
 * Procesos   *
 **************/

'sProcQuitarDoc' => "Documento Quitado",
'sProcQuitarInd' => "Quitar Indicador",
'sProcPonerDoc' => "Documento Añadido",
'sProcPonerInd' => "Indicador Añadido",
'sProcProv' => "Proveedor",
'sProcEntradas' => "Entradas",
'sProcPropietario' => "Propietario",
'sProcInd' => "Indicadores",
'sProcSalidas' => "Salidas",
'sProcCliente' => "Cliente",
'sProcInstal' => "Instalaciones y Ambiente de Trabajo",
'sProcIndicacion' => "Indicaciones",
'sProcNoDef' => "No esta definida una ficha para este proceso.",

/**********
 * Matriz *
 **********/

'sMatrProv' => "Proveedor",
'sMatrEntrada' => "Entradas",
'sMatrPropietario' => "Propietario",
'sMatrIndic' => "Indicadores",
'sMatrSalida' => "Salidas",
'sMatrCliente' => "Cliente",
'sMatrInstal' => "Instalaciones y Ambiente de Trabajo",
'sMatrDocAsoc' => "Documentacion Asociada",
'sMatrReg' => "Registros",


'sMatrNombre' => "Nombre",
'sMatrTipo' => "Tipo",
'sMatrImpacto' => "Impacto",
'sMatrArea' => "Area",
'sMatrCantidad' => "Cantidad",
'sMatrSeveridad' => "Severidad",
'sMatrFrecuncia' => "Frec./Probabilidad",
'sMatrSeverEmer' => "Sever./Emerg",
'sMatrProbabilidad' => "Probabilidad",
'sMatrSignificante' => "Significante",
'sMatrValoracion' => "Valoracion",


/************
 * Equipos  *
 ************/

'sEqNumCtrl' => "Numero Control:",
'sEqSN' => "S/N:",
'sEqDesc' => "Descripcion:",
'sEqModelo' => "Modelo:",
'sEqFabrica' => "Fabricante:",
'sEqLugar' => "Ubicacion:",
'sEqVerifInt' => "Verificacion Interna:",
'sEqCalibra' => "Calibracion",
'sEqNoUso' => "Fuera de Uso",
'sEqFechaNoUso' => "Fecha Fuera de Uso",
'sEqMotivo' => "Motivo:",


/*********************
 * Detalles Revision *
 *********************/

'sDetFecha' => "Fecha Realizacion:",
'sDetComent' => "Comentarios:",
'sDetMotivo' => "Motivo del Mantenimiento",


/**************
 * Auditorias *
 **************/

'sQuitaArea' => "Area Quitada",
'sAudPonArea' => "Area Aadida",
'sAudNombre' => "AUDITORIA",
'sAudDesc' => "Descripcion:",
'sAudMes' => "Mes Previsto:",
'sAudObserva' => "Observaciones:",
'sAudEstado' => "Estado:",
'sAudPlan' => "PLAN DE LA AUDITORIA",
'sAudTipo' => "Tipo Auditoria:",
'sAudInterna' => "Interna",
'sAudExterna' => "Externa",
'sAudRequisito' => "Requisitos a Estudiar:",
'sAudAlcance' => "Alcance:",
'sRealizado' => "Realizado",

/**********************
 * Informe: imprimir  *
 **********************/

'sPrintAud' => "AUDITORIA",
'sPrintDesc' => "Descripcion:",
'sPrintMes' => "Mes Previsto:",
'sPrintObserva' => "Observaciones:",
'sPrintEstado' => "Estado:",
'sPrintPlan' => "PLAN DE LA AUDITORIA",
'sPrintTipo' => "Tipo Auditoria:",
'sPrintInterna' => "Interna",
'sPrintExterna' => "Externa",
'sPrintReq' => "Requisitos a Estudiar:",
'sPrintAlcance' => "Alcance:",
'sPrintInforme' => "INFORME",
'sPrintRecom' => "Recomendaciones:",
'sPrintConclusion' => "Conclusiones:",
'sPrintEqAud' => "Equipo Auditor:",
'sPrintAreas' => "Areas Auditadas:",
'sPrintConforme' => "No Conformidades Detectadas:",


/*****************
 * Indicadores   *
 *****************/

'sIndNinguno' => "Ninguno",
'sIndFormValor' => "Formulario Valores",
'sIndMedicion' => "Ultima medicion:",
'sIndNunca' => "Nunca",


/***************
 * Calendario  *
 ***************/

'sCalFlechaIzq' => "<<",
'sCalFlechaDer' => ">>",
'sCalDia' => "Hoy",
'sEne' => "Ene",
'sAbr' => "Abr",
'sAgo' => "Ago",
'sDic' => "Dic",
'sEnero' => "Enero",
'sFebrero' => "Febrero",
'sMarzo' => "Marzo",
'sAbril' => "Abril",
'sMayo' => "Mayo",
'sJunio' => "Junio",
'sJulio' => "Julio",
'sAgosto' => "Agosto",
'sSeptiembre' => "Septiembre",
'sOctubre' => "Octubre",
'sNoviembre' => "Noviembre",
'sDiciembre' => "Diciembre",
'sLunes' => "Lu",
'sMartes' => "Ma",
'sMiercoles' => "Mi",
'sJueves' => "Ju",
'sViernes' => "Vi",
'sSabado' => "Sa",
'sDomingo' => "Do",

/********************
 * Proces Eliminar  *
 *******************/

'sElimFila' => "Eliminar Fila",
'sElimTable' => "que tiene el table id:",
'sElimTable2' => "en la tabla",


/***********
 * Submenu *
 ***********/

'sSubWelcomeC' => "Bienvenido a la Aplicacion de Calidad",
'sSubWelcomeA' => "Bienvenido a la Seccion de Administracion",
'sSubWelcomeM' => "Bienvenido a la aplicacion de Medio Ambiente",
'sSubCalidad' => "Calidad",
'sSubAdmin' => "Administracion",


/***************
 * Documentos  *
 ***************/

'sDocumento' => "Documento:",
'sDocRevision' => "Revision:",
'sDocEstado' => "Estado:",
'sDocRevisado' => "Revisado por:",
'sDocNuevo' => "Nuevo",
'sBorraAlert' => "Ya hay un borrador",
'sRevision' => "Revision Correcta",
'sRevAument' => "Revision aumentada",
'sDocAprobado' => "Documento Aprobado",
'sDocOpCorrecta' => "Operacion Correcta",
'sDocError' => "Operacion Erronea",
'sDocAprobar' => "Aprobado por",
'sDocBorrador' => "BORRADOR",
'sDocNoRevisado' => "No Revisado",
'sNoBorrador' => "No existe borrador",
'sNoFichBorr' => "No existe la ficha, aun en borrador",
'sNoFichCrea' => "No existe ficha,creando nueva",
'sModEditor' => "Modifique el Documento:",
'sEditorTit' => "Titulo:",
'sEditorCod' => "Codigo:",
'sEditorCalidad' => "Calidad",
'sEditorAmb' => "Medio Ambiente",
'sEditorArea' => "Area:",
'sDFlujograma' => "Flujograma:",


/***********
 * Editor  *
 ***********/

'sVacio' => "Mensaje Vaco",
'sDocExito' => "El documento se ha creado correctamente",


/***********
 * Cursos
 ***********/

'sCursoNombre' => "Curso:",
'sCursoLugar' => "Lugar:",
'sCursoDuracion' => "Duracion (horas):",
'sCursoFechaPrev' => "Fecha Prevista:",
'sCursoHoraPrev' => "Hora Prevista:",
'sCursoResponsable' => "Responsable:",
'sCursoObj' => "Objetivos:",
'sCursoCont' => "Contenidos:",
'sCursoMaterialN' => "Material Necesario:",
'sCursoMaterialS' => "Material Suministrado:",
'sCursoNoPeticion' => "No hay ninguna peticion pedida",
'sCursoNoBaja' => "No se ha solicitado ninguna baja",
'sCursoInscrito' => "Ya esta inscrito en el curso",
'sCursoSolicitado' => "Ya ha solicitado la inscripcion",
'sCursoPedirAlta' => "Alta Solicitada",
'sCursoInscripcion' => "Inscripcion realizada",
'sCursoPedirBaja' => "Baja Solicitada",
'sCursoCancel' => "Peticion de alta cancelada",
'sCursoBaja' => "Ya ha sido dado de baja del curso",
'sCursoSolBaja' => "Ya ha solicitado la baja de este curso",
'sCursoNoInscrito' => "No estaba inscrito al curso",
'sCursoNoDisp' => "El curso no esta disponible para inscripciones.",

/**************************
 * Documentacion en Vigor *
 **************************/

'sVigenteNombre' => "VIGENTE",
'sNoVersionVigor' => "No hay version en vigor",
'sProcTime' => "Procesando,esta operacion puede tardar algun tiempo,pulse OK",
'sNofichDef' => "No hay ficha definida",

/*************
 * Historico *
 *************/

'sHistorico' => "HISTORICO",

/**********
 * Tareas *
 **********/

'sTareaEnviada' => "Tarea Enviada Por:",
'sTareaEjecutar' => "Ejecutar la Accion:",
'sTareaDoc' => "Sobre el Documento:",
'sTareaDesc' => "Descripcion:",


/***************
 * Legislacion *
 ***************/

'sLegVerifica' => "Verifica",
'sLegEstado' => "Estado",
'sLegAnterior' => "Anterior",
'sLegAll' => "Todos",
'sLegSi' => "Cumple",
'sLegNo' => "No Cumple",
'sLegFicha' => "Ficha:",
'sLegContenido' => "Contenido:",


/****************
 * Cuestionario *
 ****************/

'sPregunta' => "Pregunta:",
'sRespuesta' => "Respuesta:",
'sAfirmacion' => "Si",
'sNegacion' => "No",
'sInsCorrecta' => "Insercion Correcta",
'sCuestionario' => "Cuestionario",
'sPreg' => "Pregunta",
'sRes' => "Respuesta",


/*************
 * Fichero   *
 *************/

'sEnviarFichero' => "Enviar Fichero",

'sArchivo' => "Archivo Llamado",
'sMetodo' => "Metodo",
'sVariables' => "Variables",
'sFSoportados' => "Ficheros Soportados:    ",

/***************
 * Formularios *
 ***************/

'sFormEditar' => "Editar ",
'sFormNuevo' => "Nuevo ",
'sFormClave' => "Cambiar Password",
'sFormFicha' => "Ficha de Personal",


/**************
 * Flujograma *
 **************/

'sFlujoUp' => "Flujograma Subido",
'sFicheroUp' => "Fichero Subido",
'sFNoSoportado' => "Tipo de Fichero No Soportado",
'sESubir' => "Error Subiendo Ficheros",
'sFichError' => "Fichero Erróneo",


/**********************
 * Matriz Indicadores *
 **********************/

'sMIProceso' => "Proceso",
'sMIIndicador' => "Indicador",
'sMIValorIn' => "Valor Inicial",
'sMIValorTol' => "Valor Tolerable",
'sMIObj' => "Objetivo",
'sMIMedicion' => "Metodo de Medicion",
'sMIAnalisis' => "Medicion/Analisis",
'sMIResponsable' => "Responsable de Medicion/Analisis",

/*************************
 * Párrafos de entrada   *
 *************************/

'sPInicio' => "Esta es la pagina de inicio de la aplicacion. Desde aqui se podra gestionar tanto la calidad " .
    "como los aspectos ambientales de la empresa seleccionando cualquiera de los elementos del menu superior.",

'sPDocumentacion' => "Modulo de Documentacion. Desde este modulo se puede acceder a toda la documentacion, registros y " .
    "normativas de la empresa que se encuentren disponibles. Se pueden realizar operaciones como crear, ver, editar, revisar, " .
    "aprobar documentos, y acceder a un registro con un listado de los mismos. Ademas, tambin se puede acceder a documentos externos " .
    "y ver la legislacion vigente aplicable por la empresa.",


'sPProveedores' => "Modulo de Proveedores. Desde este modulo se pueden gestionar los proveedores " .
    "y contactos de la empresa, los productos asi como las incidencias que hayan podido ocurrir.",

'sPAM' => "Modulo de Acciones de Mejora. Desde este modulo, y a traves de formularios, se podran gestionar las " .
    "acciones de mejora que se encuentren registradas, pudiendo crear nuevos registros, editar o verificar los" .
    " ya existentes",

'sPFormacion' => "Modulo de Formacion. Dentro de este modulo se encuentran las ofertas formativas a la que los usuarios " .
    "pueden inscribirse. Tambien se puede acceder a la ficha de personal de cada empleado, y ver los requisitos del" .
    " puesto de trabajo.",

'sPEquipos' => "Modulo de Equipos. Este modulo permite llevar un control de los equipos existentes en la empresa. En el " .
    "tambien se pueden definir las revisiones y planes de mantenimiento que necesiten llevarse a cabo en cada equipo. " .
    "Ademas, este modulo contiene un calendario anual en donde se podran sealar fechas relativas a la realizacion de " .
    "los planes de mantenimiento o revisiones.",

'sPAuditoria' => "Modulo de Auditorias. Este modulo permite mantener y administrar el registro de las auditoras de la empresa, " .
    "tanto realizadas como pendientes, externas o internas. Entre otras operaciones, desde este modulo se puede crear, editar " .
    "copiar o dar de baja una auditoria, hacerla vigente e incluso imprimir un informe detallado con los datos de las mismas, ",


'PProcesos' => "Modulo de Procesos. Este modulo es el encargado de gestionar los procedimientos internos de la empresa. " .
    "Entre otras operaciones, se podran crear, modificar y gestionar procesos, fichas, indicadores e incluso documentos anexos.",

'sPIndicadores' => "Modulo de Indicadores. Este modulo se encarga de registro de los indicadores de proceso. Desde aqui " .
    "un usuario puede crear nuevos indicadores, editar o dar de baja los ya existentes.",

'sPAmbientales' => "Modulo de Aspectos Ambientales. Desde este modulo se puede acceder a un listado de los diferentes " .
    "tipos de aspectos ambientales registrados en la empresa. El usuario puede tambien registrar otros nuevos, editarlos o incluso " .
    "darlos de baja.",

'sPAplicacion' => "Modulo de Administracion de la Aplicacion. En esta seccion se puede modificar todo lo referente a " .
    "la informacion de los usuarios registrados, sus claves de acceso, sus perfiles y permisos de acceso. Desde aqui " .
    "tambien se puede dar de alta o baja a las areas existentes, administrar los mensajes de los usuarios o las tareas a realizar " .
    "por los mismos.",

'sPCalidad' => "Modulo de Administracion de la Calidad. En este modulo es donde se gestiona la documentacion disponible " .
    "en la empresa, los registros y normativas, los criterios aplicados, los tipos de acciones de mejora registrados e incluso" .
    " la informacion relacionada con los clientes de la empresa.",

'sPMedio' => "Modulo de Administracion del Medio Ambiente. Desde este modulo se pueden crear o editar diferentes areas o " .
    "ambitos de aplicacion de los distintos aspectos ambientales registrados en la empresa.",


/**
 * Añadidos, ordernar luego (albatista)
 */
'sAudAreas' => "Areas",
'sTAai' => "Analisis ambiental inicial",
'sNormativa' => "Normativa",
'sAdjunto' => "Adjunto",

// formulario administracion

'sFAContenido' => "Contenido",
'sFATitulo' => "Titulo",
'sFANombre' => "Nombre",
'sFAActivo' => "Activo/Inactivo",
'sFAPerfil' => "Perfil",
'sFA1Apellido' => "Primer Apellido",
'sFA2Apellido' => "Segundo Apellido",
'sFATelefono' => "Telefono",
'sFANIF' => "NIF",
'sFAEmail' => "Email",
'sFAFicha' => "Ficha",
'sFARequisitos' => "Requisitos puesto",
'sFAContacto' => "Contacto",
'sFAValor' => "Valor",
'sFAIdioma' => "Idioma",
'sFACodigo' => "Codigo",
'sFAArea' => "Area",
'sFAPregunta' => "Pregunta",
'sFAValorDeseado' => "Valor deseado",
'sFALogin' => "Login",
'sFAPassword' => "Password",
'sFACerrar' => "Cerrar",
'sFASeleccionar' => "seleccionar",

// formulario calidad

'sFCFAX' => "Fax",
'sFCMovil' => "Movil",
'sFCActivo' => "Activo",
'sFCHomolog' => "Valor Homologacion",
'sFCCodigo' => "Codigo",
'sFCProveedor' => "Proveedor",
'sFCEntradas' => "Entradas",
'sFCPropi' => "Propietario",
'sFCSalidas' => "Salidas",
'sFCCliente' => "Cliente",
'sFCDocu' => "Documentacion Asociada",
'sFCRegistro' => "Registro",
'sFCIndica' => "Indicaciones",
'sFCInst' => "Instalaciones y ambiente de trabajo",
'sFCNControl' => "Numero de control",
'sFCDesc' => "Descripcion",
'sFCModelo' => "Modelo",
'sFCFabricante' => "Fabricante",
'sFCUbica' => "Ubicacion",
'sFCTipo' => "Tipo",
'sFCMantCada' => "Mantenimento cada",
'sFCDiasMant' => "Dias/Meses Mantenimento",
'sFCFueraUso' => "Fuera de Uso",
'sFCFechaFueraServ' => "Fecha puesta fuera de servicio",
'sFCCausa' => "Causa",
'sFCFechaRealiz' => "Fecha de realizacion",
'sFCComent' => "Comentarios",
'sFCMotivosMant' => "Motivos del mantenimento",
'sFCAccion' => "accion",
'sFCVObjetivo' => "Valor del Objetivo",
'sFCResponsable' => "Responsable",
'sFCPlazo' => "Plazo",
'sFCRecursos' => "Recursos",
'sFCObserva' => "Observaciones",
'sFCOArea' => "Area",
'sFCFecha' => "Fecha",
'sFCObjetivo' => "Objetivo",
'sFCDefinicion' => "Definicion",
'sFCValorInicial' => "Valor inicial",
'sFCValorTolerante' => "Valor Tolerable",
'sFCFrecuenciaSeg' => "Frecuencia Del Seguimiento",
'sFCResponsableSeg' => "Responsable Del Seguimiento",
'sFCFrecAnalisis' => "Frecuencia Del Analisis",
'sFCRespAnalisis' => "Responsable Del Analisis",
'sFCTecnica' => "Tecnica",
'sFCVarControl' => "Variables de Control",
'sFCGeneraObj' => "Genera Objetivo",
'sFCAreas' => "Areas",
'sFCEstado' => "Estado",
'sFCTipoAudi' => "Tipo Auditoria",
'sFCRequisitos' => "Requisitos",
'sFCAlcance' => "Alcance de la auditoria",
'sFCUsuarioInt' => "Usuario Interno",
'sFCLugar' => "Lugar",
'sFCFechaInforme' => "Fecha Informe",
'sFCConclusiones' => "Conclusiones",
'sFCRecomendaciones' => "Recomendaciones",
'sFCFechaRealizAudi' => "Fecha Realizacion Auditoria",
'sFCNombreFicha' => "Nombre Ficha",
'sFCFechaCreacion' => "Fecha Creacion",
'sFCRevision' => "Revision",
'sFCApellidos' => "Apellidos",
'sFCFechaNacim' => "Fecha de Nacimiento",
'sFCLocalidad' => "Localidad",
'sFCProvincia' => "Provincia",
'sFCPobResidencia' => "Poblacion de residencia",
'sFCProvResidencia' => "Provincia de residencia",
'sFCVehiculopropio' => "Vehiculo propio",
'sFCTitulosOfi' => "Titulos Oficiales",
'sFCFechafin' => "Fecha de finalizacion",
'sFCCentro' => "Centro",
'sFCEmpresa' => "Empresa",
'sFCFechaIncor' => "Fecha de Incorporacion",
'sFCPerfil' => "Perfil",
'sFCDepartamento' => "Departamento",
'sFCCurso1' => "Curso 1",
'sFCCurso2' => "Curso 2",
'sFCCurso3' => "Curso 3",
'sFCNivelIngles' => "Nivel de Ingles",
'sFCNivelFrances' => "Nivel de Frances",
'sFCOtros' => "Otros",
'sFCNivel' => "Nivel",
'sFCFechaInicio' => "Fecha de Inicio",
'sFCFechaFin' => "Fecha Fin",
'sFCPeriodo' => "Periodo",
'sFCFicha' => "Ficha",
'sFCPuesto' => "Puesto",
'sFCFechaCambio' => "Fecha del Cambio",
'sFCVersion' => "Version",
'sFCConocimientos' => "Conocimientos",
'sFCFunciones' => "Funciones",
'sFCNomDelPuesto' => "Nombre del puesto",
'sFCCategoria' => "Categoria",
'sFCDependeDe' => "Depende de",
'sFCArea' => "Area",
'sFCRequiereAnt' => "Requiere Antiguedad",
'sFCAntiguedad' => "Antigüedad",
'sFCAutonomiaYResp' => "Nivel de autonomia y Responsabilidad",
'sFCRelacionesYCom' => "Nivel de relaciones y comunicaciones",
'sFCLiderazgo' => "Liderazgo",
'sFCMando' => "Mando",
'sFCMotivacion' => "Motivacion",
'sFCNegociacion' => "Negociacion",
'sFCTrabajo' => "Trabajo",
'sFCFormacion' => "Formacion",
'sFCFormacionTecnica' => "Formacion Tecnica",
'sFCOpcional' => "Opcional",
'sFCHoras' => "Horas",
'sFCNumero' => "Numero",
'sFCPlanAccion' => "Plan de Accion",
'sFCFechaConsec' => "Fecha Consecucion",
'sFCVMetas' => "metas",
'sFCNombre' => "Nombre",
'sFCCalidad' => "Calidad",
'sFCIdioma' => "Idioma de la auditoria",
'sFCHorario' => "Horario",
'sFCAuditor' => "Auditor",
'sFCHorainicio' => "Hora inicio",
'sFCHorafin' => "Hora fin",
'sFCIndicadores' => "Indicadores",

// formulario comun

'sFCOContenido' => "Contenido",
'sFCODestinatario' => "Destinatario",
'sFCOTitulo' => "Titulo",
'sFCONombre' => "Nombre",
'sFCODescripcion' => "Descripcion",
'sFCOTipoCurso' => "Tipo Curso",
'sFCOObjetivos' => "Objetivos",
'sFCOContenidos' => "Contenidos",
'sFCONumeroHoras' => "Numero Horas",
'sFCOMaterialNecesario' => "Material Necesario",
'sFCOMaterialSum' => "Material Suministrado",
'sFCOActivo' => "Activo",
'sFCOFechaPrev' => "Fecha Prevista",
'sFCOResponsable' => "Responsable",
'sFCOLugar' => "Lugar",
'sFCOEstado' => "Estado",
'sFCOHojaFirmas' => "Hoja firmas",
'sFCOVerHojaFirmas' => "Ver hoja firmas",
'sFCOFechaReal' => "Fecha Realizacion",
'sFCODuracion' => "Duracion(horas)",
'sFCOObserva' => "Observaciones",
'sFCOUsuarioInt' => "Usuario Interno",
'sFCOEmpresa' => "Empresa",
'sFCOUsuario' => "Usuario",
'sFCOAccion' => "accion",
'sFCOComentarios' => "Comentarios",
'sFCOTipo' => "Tipo",
'sFCOCliente' => "Cliente",
'sFCOFecha' => "Fecha",
'sFCODetectadaPor' => "Detectada por",
'sFCOAnalisis' => "Analisis",
'sFCOReqTratamiento' => "Requiere tratamiento",
'sFCOTratInmediato' => "Tratamiento Inmediato",
'sFCOAccionCorrecPrev' => "Accion Correctora Preventiva",
'sFCOResponsableImp' => "Responsable de Implantacion",
'sFCOFechaImp' => "Fecha Implantacion",
'sFCOPlazoApro' => "Plazo Aproximado",
'sFCOCoste' => "Coste",

'sProcesoBaja' => "Proceso dado de baja",

// formulario medio

'sFMNombre' => "Nombre",
'sFMFormula' => "Formula",
'sFMLegislacionApli' => "Legislacion Aplicable",
'sFMFicha' => "Ficha",
'sFMArea' => "Area",
'sFMAmbito' => "Ambito",
'sFMMagnitud' => "Cantidad",
'sFMGravedad' => "Severidad",
'sFMFrecuencia' => "Frec./Probabilidad",
'sFMTipoAspecto' => "Tipo Aspecto",
'sFMImpactoAmbiental' => "Impacto Ambiental",
'sFMAreas' => "Areas",
'sFMSeveridad' => "Sever./Emergencia",
'sFMProbabilidad' => "Probabilidad",
'sFMObservaciones' => "Observaciones",


// Procesar Calidad

'sPCCliente' => "cliente",
'sPCDestinatario' => "destinatario",
'sPCTitulo' => "titulo",
'sPCEnviado' => "enviado",
'sPCHora' => "hora",
'sPCRemitente' => "remitente",
'sPCUsuOrigen' => "Usuario Origen",
'sPCUsuDestino' => "Usuario Destino",
'sPCDocumento' => "documento",
'sPCAccion' => "accion",
'sPCCodigo' => "codigo",
'sPCNombre' => "nombre",
'sPCTipo' => "tipo",
'sPCRevisado' => "revisado",
'sPCRevision' => "revision",
'sPCRevisadoPor' => "Revisado Por",
'sPCAprobadoPor' => "Aprobado Por",
'sPCFechaInicio' => "fecha de inicio",
'sPCFechaFin' => "fecha de fin",
'sPCFechaCambio' => "fecha de cambio",
'sPCTotal' => "Total",
'sPCMucha' => "Mucha",
'sPCBastante' => "Bastante",
'sPCPoca' => "Poca",
'sPCNinguna' => "Ninguna",
'sPCMuyAlta' => "Muy Alta",
'sPCAlta' => "Alta",
'sPCMedia' => "media",
'sPCBaja' => "baja",
'sPCNula' => "nula",
'sPCLiderazgo' => "liderazgo",
'sPCMando' => "mando",
'sPCMotivacion' => "motivacion",
'sPCNegociacion' => "negociacion",
'sPCTrabajo' => "trabajo",
'sPCFormacion' => "formacion",
'sPCTitulosOficiales' => "titulos oficiales",
'sPCFormacionTecnica' => "formacion tecnica",
'sPCFecha' => "fecha",
'sPCActivo' => "Activo",
'sPCHomologado' => "homologado",
'sPCValor' => "valor",
'sPCValoracionObtenida' => "Valoracion Obtenida",
'sPCNumeroControl' => "numero control",
'sPCPrevisto' => "previsto",
'sPCRealizacion' => "realizacion",
'sPCId' => "id",
'sPCEstado' => "estado",
'sPCVigente' => "Vigente",
'sPCAuditor' => "auditor",
'sPCInterno' => "Interno",
'sPCCurso' => "curso",
'sPCDiaRealiz' => "dia realizacion",
'sPCHoraRealiz' => "hora_realizacion",
'sPCUsuario' => "usuario",
'sPCProfesor' => "profesor",
'sPCTodas' => "Todas",
'sPCArea' => "area",
'sPCLugar' => "lugar",
'sPCEmpresa' => "empresa",
'sPCConocimientos' => "conocimientos",
'sPCFunciones' => "funciones",
'sPCOpcional' => "opcional",
'sPCHoras' => "horas",
'sPCTelefono' => "telefono",
'sPCTelefono1' => "telefono1",
'sPCTelefono2' => "telefono2",
'sPCDescripcion' => "descripcion",
'sPCProximaRev' => "proxima revision",
'sPCNinguno' => "Ninguno",
'sPCCerrada' => "cerrada",
'sPCAbierta' => "abierta",
'sPCMetas' => "metas",
'sPCValorObjetivo' => "valor_objetivo",
'sPCObservaciones' => "observaciones",
'sPCExterno' => "Externo",
'sPCPlanAccion' => "Plan accion",
'sPCFechaConsecucion' => "Fecha consecucion",
'sPCResponsable' => "Responsable",
'sPCRecursos' => "recursos",
'sPCSolicitadaAlta' => "Solicitada Alta",
'sPCSolicitadaBaja' => "Solicitada Baja",
'sPCLimpiar' => "Limpiar",
'sPCVolver' => "Volver",
'sPCVolverForm' => "Volver al Formulario",
'sPCEquipoAuditor' => "Equipo Auditor",
'sPCImprimir' => "Imprimir",
'sPCVerNoConf' => "Ver No Conformidades",
'sPCTipoGrafica' => "Tipo de grafica",
'sPCModoVis' => "Modo Visualizacion",
'sPCVerGrafica' => "Ver Grafica",
'sPCFecha_revision' => "Fecha revision",
'sPCFecha_aprovacion' => "Fecha aprobacion",


// Procesar Administracion

'sPAVersion' => "version",
'sPAPrimerApe' => "primer apellido",
'sPASegundoApe' => "segundo apellido",
'sPAEnviado' => "enviado",
'sPAHora' => "hora",
'sPAOrigen' => "origen",
'sPADestino' => "destino",
'sPAAccion' => "accion",
'sPADocumento' => "documento",
'sPAAlta' => "Alta",
'sPATitulo' => "titulo",
'sPAActivo' => "Activo",
'sPAEstado' => "estado",
'sPARevisadoPor' => "Revisado Por",
'sPAFechaRevision' => "fecha revision",
'sPAAprobadoPor' => "Aprobado Por",
'sPAFechaAprov' => "fecha aprobacion",
'sPACodigoFicha' => "codigo ficha",
'sPAAreaIncidencia' => "area incidencia",
'sPAAmbitoApli' => "ambito aplicacion",
'sPAVerifica' => "verifica",
'sPAFecha' => "fecha",
'sPAValorDeseado' => "Valor deseado",
'sPABaja' => "baja",
'sPANombre' => "nombre",
'sPANombreidioma' => "Idioma",
'sPATelefono' => "telefono",
'sPAContacto' => "contacto",
'sPACodigo' => "Codigo",
'sPATipo' => "tipo",
'sPARevision' => "revision",
'sPAValor' => "valor",
'sPABorrador' => "Borrador",
'sPARevisado' => "Revisado",
'sPAVigor' => "Vigor",
'sPACumple' => "Cumple",
'sPANoCumple' => "No Cumple",
'sPAPregunta' => "Pregunta",
'sPAPadre' => "Padre",
'sPAIdentificador' => "identificador",
'sPAVolver' => "Volver",
// Procesar Comun

'sPCOEnviado' => "enviado",
'sPCOHora' => "hora",
'sPCORemitente' => "remitente",
'sPCOUsuario' => "Usuario",
'sPCOAccion' => "accion",
'sPCONombre' => "nombre",
'sPCODestinatario' => "destinatario",
'sPCOTitulo' => "titulo",
'sPCOPrimerApe' => "Primer apellido",
'sPCOSegundoApe' => "Segundo apellido",
'sPCOCodigo' => "Codigo",
'sPCOEditar' => "Editar",
'sPCORevisar' => "Revisar",
'sPCOAprobar' => "Aprobar",
'sPCOTareas' => "Tareas",
'sPCOVer' => "Ver",
'sPCODocumentosAnexos' => "Documentos Anexos",
'sPCOFlujograma' => "Flujograma",
'sPCOArea' => "area",
'sPCOVolver' => "Volver",
'sPCONuevaVersion' => "Nueva Version",
'sPCOImprimir' => "imprimir",
'sPCOVerHistorico' => "Ver Historico",
'sPCODocument' => "document",
'sFCObservaciones' => "Observaciones",

// Procesar medio

'sPMCodigo' => "codigo",
'sPMNombre' => "nombre",
'sPMRevisado' => "revisado",
'sPMTitulo' => "titulo",
'sPMAreaIncidencia' => "area incidencia",
'sPMAmbitoApli' => "ambito aplicacion",
'sPMVerifica' => "verifica",
'sPMFecha' => "fecha",
'sPMCumplio' => "Cumplio",
'sPMTipo' => "tipo",
'sPMAspecto' => "Aspecto",
'sPMImpacto' => "impacto",
'sPMArea' => "area",
'sPMMagnitud' => "cantidad",
'sPMGravedad' => "gravedad",
'sPMFrecuencia' => "frecuencia",
'sPMValoracion' => "valoracion",
'sPMRevision' => "revision",
'sPMCumple' => "Cumple",
'sPMNoCumple' => "No Cumple",
'sPMNuncaComprobado' => "Nunca Comprobado",
'sPMBaja' => "Baja",
'sPMMedia' => "Media",
'sPMAlta' => "Alta",
'sPMExtrema' => "Extrema",
'sPMNoSignificativo' => "No Significativo",
'sPMSignificativo' => "Significativo",
'sPMSignifModerado' => "Significativo Moderado",
'sPMSignifSevero' => "Significativo Severo",
'sPMSignifCritico' => "Significativo Critico",
'sPMRiesgoBajo' => "Indice riesgo bajo",
'sPMRiesgoMedio' => "Indice riesgo medio",
'sPMRiesgoAlto' => "Indice riesgo alto",
'sPMVolver' => "Volver",

// Manejador Calidad
'sMCFirmas' => "Subir hoja de firmas",
'sMCModulo' => "modulo",
'sMCFormula' => "formula",
'sMCEnviado' => "enviado",
'sMCDocumento' => "documento",
'sMCCodigo' => "codigo",
'sMCId' => "id",
'sMCNombre' => "nombre",
'sMCFecha' => "fecha",
'sMCDescripcion' => "descripcion",
'sMCAccion' => "accion",
'sMCNumeroControl' => "Numero de Control",
'sMCRealizacion' => "realizacion",
'sMCCurso' => "curso",
'sMCNumeroMeta' => "numero_meta",
'sMCValor' => "valor",
'sMCAuditor' => "auditor",
'sMCProfesor' => "profesor",
'sMCUsuario' => "usuario",
'sMCEliminar' => "Eliminar",
'sMCVer' => "Ver",
'sMCHistorico' => "Historico",
'sMCVerTarea' => "Ver Tarea",
'sMCVerDocumento' => "Ver Documento",
'sMCSeleccionar' => "Seleccionar",
'sMCVolver' => "Volver",
'sMCAgregar' => "Agregar",
'sMCDetalles' => "Detalles",
'sMCMantPreventivo' => "Mant. Preventivo",
'sMCMantCorrectivo' => "Mant. Correctivo",
'sMCPlanMant' => "Plan Mant.",
'sMCNuevo' => "Nuevo",
'sMCEditar' => "Editar",
'sMCBaja' => "Baja",
'sMCAgregarCriterio' => "Agregar Criterio",
'sMCQuitarCriterio' => "Quitar Criterio",
'sMCCriterios' => "Criterios",
'sMCRevisar' => "Revisar",
'sMCNuevoSubproceso' => "Nuevo Subproceso",
'sMCValores' => "Valores",
'sMCObjetivos' => "Objetivos",
'sMCGrafica' => "Grafica",
'sMCEstadoDetalles' => "Estado/Detalles",
'sMCPlanAuditoria' => "Plan Auditoria",
'sMCEquipoAuditor' => "Equipo Auditor",
'sMCInforme' => "Informe",
'sMCSubirDocAdj' => "Subir Doc. Adj.",
'sMCVerDocAdj' => "Ver Doc. Adj.",
'sMCAsistentes' => "Asistentes",
'sMCProfesores' => "Profesores",
'sMCEnviarMsj' => "Enviar Msj",
'sMCAlta' => "Alta",
'sMCConfirmarAlta' => "Confirmar Alta",
'sMCConfirmarBaja' => "Confirmar Baja",
'sMCVerPDF' => "Ver PDF",
'sMCDatosPersonales' => "Datos Personales",
'sMCIncorporacion' => "Incorporacion",
'sMCFormacion' => "Formacion",
'sMCPreFormacion' => "Pre-formacion",
'sMCIdiomas' => "Idiomas",
'sMCCursos' => "Cursos",
'sMCFormacionTecnica' => "Formacion Tecnica",
'sMCExperienciaLaboral' => "Experiencia Laboral",
'sMCCambiosPerfil' => "Cambios Perfil",
'sMCCambiosDpto' => "Cambios Dpto",
'sMCDatosPuesto' => "Datos Puesto",
'sMCCompetencias' => "Competencias",
'sMCPromocion' => "Promocion",
'sMCSubProcesos' => "SubProcesos",
'sMCNuevoUnico' => "Insertar un valor",
'sMCNuevoMultiple' => "Insertar valores",
'sMCHorarioAuditorias' => "horario auditorias",
'sMCSubirFichero' => "Subir fichero",
'sMCVerFichero' => "Ver fichero",

// Manejador Administracion

'sMAEnviado' => "enviado",
'sMAOrigen' => "origen",
'sMANombre' => "nombre",
'sMAPrimerApe' => "primer_apellido",
'sMACodigo' => "codigo",
'sMATitulo' => "titulo",
'sMAPregunta' => "pregunta",
'sMAVer' => "Ver",
'sMAVolver' => "Volver",
'sMANuevo' => "Nuevo",
'sMAEditar' => "Editar",
'sMADarDeBaja' => "Dar de Baja",
'sMAAccion' => "Accion",

// Manejador Comun

'sMCOEnviado' => "enviado",
'sMCOEliminar' => "Eliminar",
'sMCOVer' => "Ver",
'sMCOHistorico' => "Historico",
'sMCOVolver' => "Volver",
'sMCOSeleccionar' => "Seleccionar",
'sMCOCerrar' => "Cerrar",
'sMCORevision' => "revision",
'sMCONombre' => "nombre",


// Manejador Medio

'sMMTitulo' => "titulo",
'sMMCodigo' => "codigo",
'sMMId' => "id",
'sMMFecha' => "fecha",
'sMMVerPreguntas' => "Ver Preguntas",
'sMMVolver' => "Volver",
'sMMSignificancia' => "Significancia",
'sMMImprimir' => "Imprimir",

// Form Administrar

'sFATipo' => "Tipo",
'sFATipoListado' => "Listado",
'sFATipoUnico' => "Unico",
'sFAAccion' => "Accion",
'sFAPadre' => "Padre",

// Form Administrar ayuda

'sFAAIdioma' => "Idioma",
'sFAAMenu' => "Menu",
'sFAABoton' => "Boton",
'sFAATexto' => "Texto",
'sFAACastellano' => "Castellano",
'sFAACatalan' => "Catalan",

// Forms

'sFMensajeGeneral' => "Mensaje General",
'sFMensaje' => "Mensaje",
'sFTarea' => "Tarea",
'sFArea' => "Area",
'sFTipoArea' => "Tipo Area",
'sFTipoAmbiente' => "Tipo Ambiente",
'sFCriterio' => "Criterio",
'sFTipoDocumento' => "Tipo documento",
'sFAyuda' => "Ayuda",
'sFUsuario' => "Usuario",
'sFImpacto' => "Impacto",
'sFPerfil' => "Perfil",
'sFCliente' => "Cliente",
'sFMejora' => "Mejora",
'sFNormativa' => "Normativa",
'sFProceso' => "Proceso",
'sFContenidoProceso' => "Contenido Proceso",
'sFIndicador' => "Indicador",
'sFValor' => "Valor",
'sFObjetivo' => "Objetivo",
'sFPlan' => "Plan",
'sFCurso' => "Curso",
'sFProfesor' => "Profesor",
'sFCursoPlan' => "Curso Plan",
'sFAlumno' => "Alumno",
'sFMensajeAllUsers' => "Mensaje a todos los usuarios",
'sFLegislacion' => "Legislacion",
'sFProveedor' => "Proveedor",
'sFIncidencia' => "Incidencia",
'sFContacto' => "Contacto",
'sFProducto' => "Producto",
'sFAccMejora' => "Accion de Mejora",
'sFProgramaAuditoria' => "Programa de Auditoria",
'sFAuditoria' => "Auditoria",
'sFPlanAuditoria' => "Plan Auditoria",
'sFAuditor' => "Auditor",
'sFInforme' => "Informe",
'sFEquipo' => "Equipo",
'sFMantPrev' => "Mantenimiento Preventivo",
'sFMantCorrec' => "Mantenimiento Correctivo",
'sFAspectoAmbiental' => "Aspecto Ambiental",
'sFFichaPersonal' => "Ficha de Personal",
'sFFichaPersonalPreform' => "Ficha de Personal Pre-Formacion",
'sFFichaPersonalIdiomas' => "Ficha de Personal Idiomas",
'sFRequisitosProm' => "Requisitos del Puesto Promocion",
'sFRequisitosPuesto' => "Requisitos del Puesto Datos del puesto",
'sFFormacionTecnica' => "Formacion Tecnica",
'sFExperienciaLaboral' => "Experiencia Laboral",
'sFCambioPerfil' => "Cambio de perfil",
'sFCambioDepartamento' => "Cambio de departamento",
'sFMeta' => "Meta",
'sFReqPuestoComp' => "Requisitos del Puesto Competencias",
'sFReqPuestoFormacion' => "Requisitos del Puesto Formacion",
'sFReqPuestoFormTec' => "Requisitos del Puesto Formacion Tecnica",
'sFPreguntasLegislacion' => "Preguntas Legislacion",
'sFTipoCurso' => "Tipo de Curso",
'sFNuevo' => "Nuevo",
'sFVolver' => "Volver",
'sFIdioma' => "Idioma",
'sFBoton' => "Boton",
'sFIdiomaBoton' => "Idioma Boton",
'sFIdiomaMenu' => "Idioma Menu",
'sFObjetivosGlobales' => "Objetivos globales: ",
'sFMagnitud' => "Cantidad",
'sFFrecuencia' => "Frecuencia/Probabilidad",
'sFGravedad' => "Severidad",
'sFSeguimiento' => "Seguimiento",
'sFSeveridad' => "Severidad/Emergencia",

// Manejador nuevo

'sMNIdiomas' => "idioma",
'sMNAccion' => "accion",
'sMNArea' => "area",
'sMNValor' => "valor",
'sMNNombre' => "nombre",
'sMAActualizar' => "Actualizar",

// Procesar nuevo

'sPNAccion' => "accion",
'sPNTipo' => "tipo",
'sPNPermisos' => "permisos",
'sPNValor' => "valor",
'sPNIdioma' => "idioma",
'sPNHorainicio' => "hora inicio",
'sPNHorafin' => "hora fin",
'sPNArea' => "area",
'sPNAuditor' => "auditor",
'sPNRequisitos' => "requisitos",
'sPNNombre' => "nombre",
'sPNPerfilVer' => "Perfil ver",
'sPNPerfilNueva' => "Perfil nueva",
'sPNPerfilModificar' => "Perfil modificar",
'sPNPerfilRevisar' => "Perfil revisar",
'sPNPerfilAprobar' => "Perfil aprobar",
'sPNPerfilHistorico' => "Perfil historico",
'sPNPerfilTareas' => "Perfil tareas",
'sPNActualizar' => "Actualizar",
'sPNVolver' => "Volver",
'sPNPermisosAct' => "Permisos actualizados correctamente",


// form nuevo

'sFNAccion' => "Accion",
'sFNTipo' => "Tipo",
'sFNValor' => "Valor",
'sFNNombre' => "Nombre",

// Procesar detalles

'sPDVolver' => "Volver",

// Manejador Listado

'sMLAgregar' => "Agregar",
'sMLVolver' => "Volver",
'sMLAgregarCriterio' => "Agregar Criterio",
'sMLQuitarCriterio' => "Quitar Criterio",

// Procesar detalles

'sPLVer' => "Ver",
'sPLNuevaVersion' => "Nueva version",

//PDF de indicadores-objetivos
'sIOObjetivos' => "OBJETIVOS:",
'sIOResp' => "Responsable:",
'sIOPlazo' => "PLAZO:",
'sIOAccion' => "ACCION:",
'sIORecursos' => "RECURSOS:",
'sIOMetas' => "Meta Numero:",
'sIODesc' => "Descripcion",
'sIOVerificado' => "VERIFICADO POR:",
'sIOFirma' => "Firma y fecha",
'sIOAprobado' => "APROBADO POR:",
'sIOIndicador' => "INDICADOR:",
'sIOFecha' => "Fecha:",
'sIOPlanAccion' => "Plan Accion:",

// Procesar Funciones comunes
'sPFCExisteManual' => "Ya existe un Manual",
'sPFCExistePolitica' => "Ya existe una Politica",
'sPFCExisteAAI' => "Ya existe un Analisis Ambiental Inicial",


// Ayuda
'sAMenu' => "Menu",
'sAIdioma' => "Idioma",
'sATexto' => "Texto",
'sABoton' => "Boton",


/*
   *  entradas para creaficha.php
   */

'sCFFICHADEPERSONAL' => "FICHA DE PERSONAL",
'sCFNombre' => "Nombre",
'sCFApellidos' => "Apellidos",
'sCFFechaNac' => "Fecha de Nacimiento",
'sCFFOTO' => "FOTO",
'sCFDireccion' => "Dirección",
'sCFVehiculoprop' => "Vehiculo propio",
'sCFLocalidad' => "Localidad",
'sCFProvincia' => "Provincia",
'sCFTelefono' => "Telefono",
'sCFPoblacion' => "Poblacion",
'sCFObservaciones' => "Observaciones",
'sCFProvinciaRes' => "Provincia Res",
'sCFTitulosOficiales' => "Titulos Oficiales",
'sCFFechaFin' => "Fecha Fin",
'sCFCentro' => "Centro",
'sCFCoste' => "COSTE",
'sCFCerradopor' => "CERRADO POR",
'sCFEmpresa' => "Empresa",
'sCFFechaIncorp' => "Fecha Incorporacion",
'sCFPerfil' => "Perfil",
'sCFDepartamento' => "Departamento",
'sCFFechacambioperfil' => "Fecha cambio perfil",
'sCFFechacambiodep' => "Fecha cambio departamento",
'sCFCurso' => "Curso",
'sCFIngles' => "Ingles",
'sCFNivel' => "Nivel",
'sCFFrances' => "Frances",
'sCFOtros' => "Otros",
'sCFPuestocargo' => "Puesto/cargo",
'sCFFechaInicio' => "Fecha Inicio",
'sCFFormacionComp' => "Formación Complementaria",
'sCFNombreCurso' => "Nombre Curso",
'sCFLugarimparticion' => "Lugar imparticion",
'sCFDuracion' => "Duracion",
'sCFDesde' => "Desde",
'sCFHasta' => "Hasta",
'sCFPeriodotiempo' => "Periodo tiempo",
'sCFRequisitos' => "Requisitos para el puesto",
'sCFNombrepuestotrab' => "Nombre del puesto de trabajo",
'sCFCategoria' => "Categoria",
'sCFDependede' => "Depende de",
'sCFArea' => "Area",
'sCFAntiguedad' => "Antigüedad requerida",
'sCFSi' => "Si",
'sCFNo' => "No",
'sCFNYears' => "Número Años",
'sCFFormacionTecnica' => "Formacion Tecnica",
'sCFOpcional' => "Opcional",
'sCFHoras' => "Horas",
'sCFAutonomiayresp' => "Nivel de autonomia y responsabilidad",
'sCFRelacionesyCom' => "Nivel de Relaciones y Comunicaciones",
'sCFHabilidadessociales' => "Habilidades sociales",
'sCFLiderazgoyevaluacion' => "Liderazgo y evaluacion",
'sCFTotal' => "Total",
'sCFMuyAlta' => "Muy Alta",
'sCFMandoEvaluacion' => "Mando/Evaluacion",
'sCFMucha' => "Mucha",
'sCFAlta' => "Alta",
'sCFMotivacionDelegacion' => "Motivacion/Delegacion",
'sCFBastante' => "Bastante",
'sCFMedia' => "Media",
'sCFNegociacion' => "Negociacion",
'sCFPoca' => "Poca",
'sCFBaja' => "Baja",
'sCFTrabajoequipo' => "Trabajo en equipo",
'sCFNinguna' => "Ninguna",
'sCFNula' => "Nula",
'sCFFormacionEnse' => "Formacion/Enseñanza",
'sCFAccionmejora' => "ACCIÓN DE MEJORA",
'sCFNC' => "NC",
'sCFReclamacion' => "Reclamacion",
'sCFAuditoria' => "Auditoria",
'sCFPreventiva' => "Preventiva",
'sCFIdentificacion' => "IDENTIFICACION",
'sCFCliente' => "CLIENTE",
'sCFProductoproyecto' => "PRODUCTO O PROYECTO",
'sCFFecha' => "FECHA",
'sCFDetectadapor' => "DETECTADA POR",
'sCFDescripcion' => "DESCRIPCION",
'sCFAnalisis' => "ANÁLISIS",
'sCFTratamientoinmediato' => "TRATAMIENTO INMEDIATO",
'sCFNotiene' => "No tiene",
'sCFAccionCORPREV' => "ACCION CORRECTIVA/PREVENTIVA",
'sCFResponsableimp' => "RESPONSABLE IMPLANTACION",
'sCFPlazoaproximado' => "PLAZO APROXIMADO",
'sCFVerificadopor' => "VERIFICADO POR",
'sCFFirmayfecha' => "Firma y fecha",
'sErrorNoEncontrado' => "El fichero solicitado no se encuentra en el sistema",
'sErrorNoICS' => "Opcion solo valida desde ICS",
'sHospital' => "Hospital",
'sDbExiste' => "Ya ha sido generada la base de datos asociada al hospital",
'sDbCreada' => "Base de datos creada",
'sDbErrorHospital' => "Se ha producido un error en la aplicacion",

// procesar listado

'sPLCodigo' => "Codigo",
'sPLNombre' => "Nombre",
'sPLTipo' => "Tipo",
'sPLCurso' => "Curso",
'sPLDescripcion' => "Descripcion",
'sPLArea' => "Area",
'sPLAspecto' => "Aspecto",
'sPLImpacto' => "Impacto",
'sPLPrimerApe' => "Primer Apellido",
'sPLTitulo' => "Titulo",
'sPLEnviado' => "Enviado",
'sPLOrigen' => "Origen",
'sPLDestino' => "Destino",
'sPLAccion' => "Accion",
'sPLDocumento' => "Documento",
'sPLValor' => "Valor",
'sPLPadre' => "Padre",
'sPLIdioma' => "Idioma",
'sPLMenu' => "Menu",
'sPLBoton' => "Boton",
'sPLRemitente' => "Remitente",
'sBajarxls' => "Bajar xls",
);


$fh = fopen("en.po", 'w');
fwrite($fh, "#\n");
fwrite($fh, "msgid \"\"\n");
fwrite($fh,  "msgstr \"\"\n");

foreach ($LANG as $key => $value) {
    $key = addslashes($key);
    $value = addslashes($value);
    fwrite($fh, "\n");
    fwrite($fh, "msgid \"$key\"\n");
    fwrite($fh, "msgstr \"$value\"\n");
}
fclose($fh);