-- ============================================================================
-- 0004-full-legacy-menu.sql
-- Full real legacy menu imported for renderer verification and module planning.
-- Generated automatically. Safe to re-apply.
-- ============================================================================

-- menu_nuevo (full set from legacy)
INSERT INTO menu_nuevo (id, padre, orden, accion, permisos, activo) VALUES
(1, 65, 75, 'messages:get', '[0:22]={f,f,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f}', true),
(2, 65, 76, 'inicio:tareas:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(3, 77, 79, 'documentacion:manual:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(4, 77, 83, 'documentacion:politica:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(5, 77, 82, 'documentacion:objetivos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(7, 77, 80, 'documentacion:pg:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(8, 77, 84, 'documentacion:pe:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(9, 78, 90, 'documentacion:frl:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(10, 77, 87, 'documentacion:docvigor:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(11, 79, 93, 'documentacion:registros:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(12, 78, 91, 'documentacion:legislacion:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(13, 79, 94, 'documentacion:docformatos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(14, 68, 15, 'mejora:listado:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(15, 80, 18, 'formacion:fichapersonal:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(16, 80, 19, 'formacion:reqpuesto:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(17, 81, 21, 'formacion:cursos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(18, 81, 22, 'formacion:inscripcion:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(19, 81, 23, 'formacion:planes:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(20, 70, 13, 'equipos:listado:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(21, 70, 12, 'equipos:revision:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(22, 70, 11, 'equipos:calendario:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(23, 71, 25, 'auditorias:programa:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(24, 71, 26, 'auditorias:plan:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(26, 73, 32, 'aambientales:revision:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(27, 73, 31, 'aambientales:matriz:detalles:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(28, 76, 3, 'procesos:catalogos:arbol:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(31, 72, 28, 'indicadores:indicadores:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(32, 82, 40, 'administracion:usuarios:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(33, 82, 41, 'administracion:perfiles:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(35, 82, 42, 'messages:get', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(36, 82, 43, 'administracion:tareas:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(37, 83, 49, 'administracion:documentossg:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(38, 83, 48, 'administracion:registros:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(39, 83, 50, 'administracion:normativa:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(40, 84, 38, 'administracion:criterios:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(41, 85, 52, 'administracion:tipomejora:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(42, 86, 36, 'administracion:clientes:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(43, 87, 54, 'administracion:tiposareas:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(44, 88, 56, 'administracion:tiposamb:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(45, 67, 5, 'proveedores:listado:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(46, 67, 6, 'proveedores:incidencias:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(47, 67, 7, 'proveedores:contactos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(48, 67, 8, 'proveedores:productos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(49, 67, 9, 'proveedores:phomologados:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(50, 72, 29, 'indicadores:objetivos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(55, 89, 58, 'administracion:legaplicable:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(57, 77, 81, 'documentacion:docborrador:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(58, 90, 60, 'administracion:tiposimp:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(61, 91, 62, 'administracion:tipo_cursos:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(62, 77, 86, 'documentacion:aai:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(63, 78, 89, 'documentacion:normativa:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(64, 92, 64, 'administracion:tipodocumento:listado:nuevo', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(65, 0, 74, 'inicio', '[0:22]={f,f,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,t,f,f,f}', true),
(66, 0, 77, 'documentacion', '[0:22]={f,f,f,f,f,f,f,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(67, 0, 4, 'proveedores', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(68, 0, 14, 'mejora', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(69, 0, 16, 'formacion', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(70, 0, 10, 'equipos', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(71, 0, 24, 'auditorias', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(72, 0, 27, 'indicadores', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(73, 0, 30, 'maspectos', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(74, 0, 34, 'administracion', '[0:22]={f,f,f,f,f,f,f,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(75, 0, 95, 'logout', '[0:22]={f,f,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f}', true),
(76, 0, 2, 'procesos', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(77, 66, 78, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(78, 66, 88, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(79, 66, 92, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(80, 69, 17, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(81, 69, 20, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(82, 74, 39, NULL, '[0:22]={f,f,f,f,f,f,f,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(83, 74, 47, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(84, 74, 37, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(85, 74, 51, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(86, 74, 35, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(87, 74, 53, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(88, 74, 55, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(89, 74, 57, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(90, 74, 59, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(91, 74, 61, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(92, 74, 63, NULL, '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(93, 82, 44, 'administracion:menus:listado:nuevo', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(94, 82, 45, 'administracion:idiomas:listado:nuevo', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(95, 74, 65, '', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(96, 95, 68, 'administracion:aspectos:listado:magnitud', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(97, 95, 69, 'administracion:aspectos:listado:gravedad', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(98, 95, 70, 'administracion:aspectos:listado:frecuencia', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(100, 95, 66, 'administracion:aspectos:listado:formula', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(101, 73, 33, 'aambientales:revisionemergencia:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(102, 95, 67, 'administracion:aspectos:listado:probabilidad', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(103, 95, 71, 'administracion:aspectos:listado:severidad', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(104, 77, 85, 'documentacion:planamb:listado:ver', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(106, 74, 72, 'administracion:ayuda:listado:nuevo', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(107, 74, 73, 'administracion:modulos:listado:nuevo', '{f,t,f,f,f,f,f,f,f,f,f,f,f,f,t,f,f,f,f,f,f,f}', true),
(108, 82, 46, 'administracion:hospitales:listado:nuevo', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(109, 74, 109, '', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(110, 109, 110, 'administracion:proveedores:listado:ver', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(111, 109, 110, 'administracion:proveedores:listado:incidencia', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(112, 109, 112, 'administracion:proveedores:listado:contacto', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(113, 109, 113, 'administracion:proveedores:listado:producto', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(114, 74, 114, '', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(115, 114, 115, 'administracion:equipos:listado:ver', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(116, 74, 116, '', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(117, 116, 117, 'administracion:auditoriaanual:listado:ver', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(118, 116, 118, 'administracion:auditoriavigor:listado:ver', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(119, 74, 119, '', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true),
(120, 119, 120, 'administracion:indicadoresobjetivo:listado:ver', '{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}', true)
ON CONFLICT (id) DO NOTHING;

-- menu_idiomas_nuevo (labels)
INSERT INTO menu_idiomas_nuevo (menu, idioma_id, valor) VALUES
(1, 1, 'Mensajes'),
(1, 2, 'Missatges'),
(2, 1, 'Tareas'),
(2, 2, 'Tasques'),
(3, 1, 'Manual'),
(3, 2, 'Manual'),
(4, 1, 'Politica'),
(4, 2, 'Politica'),
(5, 1, 'Objetivos'),
(5, 2, 'Objectius'),
(7, 1, 'P.G.'),
(7, 2, 'P.G.'),
(8, 1, 'P.O.'),
(8, 2, 'P.O.'),
(9, 1, 'F.R.L'),
(9, 2, 'F.R.L'),
(10, 1, 'Doc. Vigor'),
(10, 2, 'Doc. Vigor'),
(11, 1, 'Registros'),
(11, 2, 'Registres'),
(12, 1, 'Listado'),
(12, 2, 'Llistat'),
(13, 1, 'Doc. y Formatos'),
(13, 2, 'Doc. i Formats'),
(14, 1, 'Listado'),
(14, 2, 'Llistat'),
(15, 1, 'Ficha Personal'),
(15, 2, 'Fitxa Personal'),
(16, 1, 'Req. Puesto'),
(16, 2, 'Req. Lloc'),
(17, 1, 'Cursos'),
(17, 2, 'Cursos'),
(18, 1, 'Inscripcion'),
(18, 2, 'Inscripcion'),
(19, 1, 'Planes Form.'),
(19, 2, 'Plans Form.'),
(20, 1, 'Listado'),
(20, 2, 'Llistat'),
(21, 1, 'Revisiones'),
(21, 2, 'Revisions'),
(22, 1, 'Calendario'),
(22, 2, 'Calendari'),
(23, 1, 'Programa Anual'),
(23, 2, 'Programa Anual'),
(24, 1, 'Programa en Vigor'),
(24, 2, 'Programa en Vigor'),
(26, 1, 'Aspectos Ambientales'),
(26, 2, 'Aspectes Ambientals'),
(27, 1, 'Matriz A. Amb.'),
(27, 2, 'Matriu A. Amb.'),
(28, 1, 'Catalogo'),
(28, 2, 'Catalogo'),
(31, 1, 'Indicadores'),
(31, 2, 'Indicadors'),
(32, 1, 'Usuarios'),
(32, 2, 'Usuaris'),
(33, 1, 'Perfiles'),
(33, 2, 'Perfils'),
(35, 1, 'Mensajes'),
(35, 2, 'Missatges'),
(36, 1, 'Tareas'),
(36, 2, 'Tasques'),
(37, 1, 'Documentos S.G'),
(37, 2, 'Documents S.G '),
(38, 1, 'Registros'),
(38, 2, 'Registres'),
(39, 1, 'Doc. y Formatos'),
(39, 2, 'Doc. i Formats'),
(40, 1, 'Criterios'),
(40, 2, 'Criteris'),
(41, 1, 'Tipos Acc. Mejora'),
(41, 2, 'Tipus Acc. Millora'),
(42, 1, 'Clientes'),
(42, 2, 'Clients'),
(43, 1, 'Tipos Area'),
(43, 2, 'Tipus Area'),
(44, 1, 'T. Amb. Aplicacion'),
(44, 2, 'T. Amb. Aplicacion'),
(45, 1, 'Listado'),
(45, 2, 'Llistat'),
(46, 1, 'Incidencias'),
(46, 2, 'Incid�ncies'),
(47, 1, 'Contactos'),
(47, 2, 'Contactes'),
(48, 1, 'Productos'),
(48, 2, 'Productes'),
(49, 1, 'P. Homologados'),
(49, 2, 'P. Homologats'),
(50, 1, 'Objetivos'),
(50, 2, 'Objectius'),
(55, 1, 'Leg. Aplicable'),
(55, 2, 'Leg. Aplicable'),
(57, 1, 'Doc. Borrador'),
(57, 2, 'Doc. Esborrador'),
(58, 1, 'Tipos Imp. Amb.'),
(58, 2, 'Tipus Imp. Amb.'),
(61, 1, 'Tipo Cursos'),
(61, 2, 'Tipus Cursos'),
(62, 1, 'Analisis Amb. Inicial'),
(62, 2, 'Analisis Amb. Inicial'),
(63, 1, 'Normativa'),
(63, 2, 'Normativa'),
(64, 1, 'Tipo documento'),
(64, 2, 'Tipus documento'),
(65, 1, 'INICIO'),
(65, 2, 'INICI'),
(66, 1, 'DOCUMENTACION'),
(66, 2, 'DOCUMENTACION'),
(67, 1, 'PROVEEDORES'),
(67, 2, 'PROVE�DORS'),
(68, 1, 'ACC. MEJORA'),
(68, 2, 'ACC. MILLORA'),
(69, 1, 'FORMACION'),
(69, 2, 'FORMACION'),
(70, 1, 'EQUIPOS'),
(70, 2, 'EQUIPS'),
(71, 1, 'AUDITORIAS'),
(71, 2, 'AUDITORIAS'),
(72, 1, 'INDICADORES'),
(72, 2, 'INDICADORS'),
(73, 1, 'A. AMBIENTALES'),
(73, 2, 'A. AMBIENTALES'),
(74, 1, 'ADMINISTRACION'),
(74, 2, 'ADMINISTRACION'),
(75, 1, 'CERRAR SESION'),
(75, 2, 'TANCAR SESION'),
(76, 1, 'PROCESOS'),
(76, 2, 'PROCESOS'),
(77, 1, 'Documentos S.G.'),
(77, 2, 'Documents S.G.'),
(78, 1, 'Legislacion'),
(78, 2, 'Legislacion'),
(79, 1, 'Documentos Asociados'),
(79, 2, 'Documents Associats'),
(80, 1, 'Recursos'),
(80, 2, 'Recursos'),
(81, 1, 'Formacion'),
(81, 2, 'Formacion'),
(82, 1, 'Aplicacion'),
(82, 2, 'Aplicacion'),
(83, 1, 'Documentos'),
(83, 2, 'Documents'),
(84, 1, 'Criterios'),
(84, 2, 'Criteris'),
(85, 1, 'Tipos Acc. Mejora'),
(85, 2, 'Tipus Acc. Millora'),
(86, 1, 'Clientes'),
(86, 2, 'Clients'),
(87, 1, 'Tipos area'),
(87, 2, 'Tipus area'),
(88, 1, 'T. Amb. Aplicacion'),
(88, 2, 'T. Amb. Aplicacion'),
(89, 1, 'Log. Aplicable'),
(89, 2, 'Log. Aplicable'),
(90, 1, 'Tipos Imp. Amb.'),
(90, 2, 'Tipus Imp.Amb.'),
(91, 1, 'Formacion'),
(91, 2, 'Formacion'),
(92, 1, 'Tipo documento'),
(92, 2, 'Tipus document'),
(93, 1, 'Menus'),
(93, 2, 'Menus'),
(94, 1, 'Idiomas'),
(94, 2, 'Idiomes'),
(95, 1, 'Aspectos Ambientales'),
(95, 2, 'Aspectes Ambientals'),
(96, 1, 'Cantidad'),
(96, 2, 'Quantitat'),
(97, 1, 'Severidad'),
(97, 2, 'Severitat'),
(98, 1, 'Frec./Severidad'),
(98, 2, 'Freq./Severitat'),
(100, 1, 'Formula'),
(100, 2, 'Formula'),
(101, 1, 'Aspectos Ambientales Emergencia'),
(101, 2, 'Aspectes Ambientals Emergencia'),
(102, 1, 'Probabilidad'),
(102, 2, 'Probabilitat'),
(103, 1, 'Sever./Emergencia'),
(103, 2, 'Sever./Emergencia'),
(104, 1, 'Plan Emerg. Amb.'),
(104, 2, 'Pla Emerg. Amb.'),
(106, 1, 'Ayuda'),
(106, 2, 'Ajuda'),
(107, 1, 'Permisos'),
(107, 2, 'Permisos'),
(108, 1, 'Hospitales'),
(108, 2, 'Hospitals'),
(109, 1, 'Proveedores'),
(109, 2, 'Proveidors'),
(110, 1, 'Listado'),
(110, 2, 'Llistat'),
(111, 1, 'Incidencias'),
(111, 2, 'Incidencies'),
(112, 1, 'Contactos'),
(112, 2, 'Contactes'),
(113, 1, 'Productos'),
(113, 2, 'Productes'),
(114, 1, 'Equipos'),
(114, 2, 'Equips'),
(115, 1, 'Listado'),
(115, 2, 'Llistat'),
(116, 1, 'Auditorias'),
(116, 2, 'Auditorias'),
(117, 1, 'Auditoria anual'),
(117, 2, 'Auditoria anual'),
(118, 1, 'Auditoria en vigor'),
(118, 2, 'Auditoria en vigor'),
(119, 1, 'Indicadores'),
(119, 2, 'Indicadors'),
(120, 1, 'Objetivos'),
(120, 2, 'Objectius')
ON CONFLICT (menu, idioma_id) DO NOTHING;

-- Total: 106 menu items, 212 labels.
